### PR TITLE
Changes to the time.strftime to make it more accurate

### PR DESCRIPTION
**Pull request by spirillen**
Since some host files might need to be updated more frequently it's more appropriate to show timezone and the exact time for last build, hince changed the order of month and date to %d %B

### CODE REVIEW

**Comment by funilrys** [comment]
Why don't you use `%Z` instead of the explicit `(UTC)` ?

Otherwise, looks good to me :+1: 

P.S: Why don't we use the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format? :smile:

**Comment by funilrys** [comment]
To complete the example of @lightswitch05 we could implement it with:
```python
>> from datetime import datetime, timezone
>> datetime.now(timezone.utc).isoformat(sep=' ', timespec='seconds')
'2018-11-20 22:42:32+00:00'
>> 
```

Docs:
* https://docs.python.org/3/library/datetime.html#datetime.datetime.now
* https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat

**Comment by StevenBlack** [comment]
@spirillen will you be making the changes suggested by Daniel @lightswitch05 and Nissar @funilrys?

**Comment by funilrys** [comment]
Between, I made a mistake.

It should be:

```python
>> from datetime import datetime, timezone
>> datetime.now(timezone.utc).isoformat(timespec='seconds')
'2018-11-30T05:28:49+00:00'
>> 
```

Indeed, it does not comply to ISO 8601 without the `T`.

**Comment by spirillen** [comment]
Hi Sorry for the long response but have been down with pneumonia

But good suggestions, let me follow up on this

**Comment by StevenBlack** [comment]
Thanks @spirillen.  Merging.

**Pull request merged**
