### PR TITLE
use `/usr/bin/env sudo` for cross-compatible sudo

### PR DESCRIPTION
**Pull request by stites**
Just a simple ternary operator since this will cover almost every case I can think of.

### CODE REVIEW

**Comment by rautamiekka** [comment]
May I suggest `/usr/bin/env sudo` instead as an universal solution ? It uses the environment to find `sudo`, no matter where it may be.

**Comment by stites** [comment]
Much better, thanks @rautamiekka!

**Comment by gfyoung** [comment]
@StevenBlack : Odd that this one was forgotten about.  In any case, I think this looks good to go.  Do you mind restarting the tests?

**Comment by FadeMind** [comment]
@StevenBlack  please close this PR cause issues. New one waiting (fixed).

**Comment by FadeMind** [comment]
@gfyoung See https://github.com/StevenBlack/hosts/pull/519/commits/ee411d82c9c00fffcc22a4c8a7496dd6304aaf3b

**Comment by gfyoung** [comment]
Ah, gotcha.  I suppose this one has gone stale too...

**Comment by stites** [comment]
Hmm... so I don't really understand what the difference between these two PRs is other than the fact that this one went stale. Looking at https://github.com/StevenBlack/hosts/pull/439/files and https://github.com/StevenBlack/hosts/pull/519/files the diffs look identical. Can someone enlighten me?

**Comment by gfyoung** [comment]
@FadeMind explained it <a href="https://github.com/StevenBlack/hosts/pull/439#issuecomment-370165333">above</a>.  You had some linter errors that needed to be patched.  Since we couldn't fix your branch directly, @FadeMind just submitted another PR that encompassed yours with the fixes.

**Comment by gfyoung** [comment]
Huh, that's odd...you're right.  I guess we didn't need to create another PR for this 😄 

cc @StevenBlack

**Comment by stites** [comment]
Okay, so yeah. I'm not crazy. I'm seeing this: https://travis-ci.org/StevenBlack/hosts/jobs/303162997#L86 It would be insane to think that Travis checks intermediate commits. It also looks like @FadeMind introduced those linter errors in a previous commit on their own branch. This PR only contains one commit.

**Pull request closed without merging**
