### PR TITLE
Adding 5fd74.v.fwmrm.net

### PR DESCRIPTION
**Pull request by cgimenes**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi Marcelo @cgimenes.

Why should we block this?  Please explain.

Also, please note that all `hosts` files in the root and `alternates` folder are **generated products** from the `hosts` files in the `data` folders.  Please see the [How can I contribute hosts records?](https://github.com/StevenBlack/hosts) section in the readme.

Closing this.  Please resubmit with a proper explanation, and by changing the appropriate file here, or in the repos of our other [sources of hosts data](https://github.com/StevenBlack/hosts).

**Comment by cgimenes** [comment]
It is from Freewheel Media.
You already have some of their domains listed in this file.

**Comment by dnmTX** [comment]
Steve @StevenBlack i just checked and it's from inline script in `www.crunchyroll.com`:
Capture

...also it's probably appropriate `mssl.fwmrm.net` to be blocked as well?
Capture1

**Comment by cgimenes** [comment]
Maybe I hadn't the patience to answer it back then hahaha.
But I completely forgot about it until today, when I saw it without merge and thought about answering.

**Comment by dnmTX** [comment]
@jawz101 you have some listed in your repo. You mind adding those two as well?
Also to your attention i stumbled upon this:
hosts
Can you inspect please(you have it blocked in your list). Thank you 👍

**Comment by jawz101** [comment]
I removed that one.  Looks like the domain belongs to FreeWheel by Comcast- a targeted ad placement product.  https://www.freewheel.com/

**Comment by dnmTX** [comment]
@jawz101 what about:
`0.0.0.0 5fd74.v.fwmrm.net`
`0.0.0.0 mssl.fwmrm.net`
can you add them to your list?

**Pull request closed without merging**
