### PR TITLE
Refactor out source data updating

### PR DESCRIPTION
**Pull request by gfyoung**
I was going to refactor `settings` out of `create_initial_file`, when I found that there was this entire block of logic in there updating the `sourcedata` field in `settings` that could be abstracted out into its own method, thereby partially addressing what I had set out to do.

Follow-up to #379.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @ScriptTiger, can you review this in light of the changes I've made to remove .zip support from the repo?  Maybe close and resubmit because, well, removing .zip files and the attendant cleanup pollutes this PR somewhat  😄

**Comment by gfyoung** [comment]
@StevenBlack : Yikes!  What happened here?  It looks like you did some force-pushing on the `master` branch, causing this PR to blow up like this.  I think in the future, it would preferable, if you did not do that, as that can make it harder for others to keep their forks synchronized.

**Comment by gfyoung** [comment]
@StevenBlack : Luckily, my commits were not overlapping with your changes, so a hard reset of my branches followed by reapplying the changes did the trick.  Still, would have been nicer if there was no force-push to `master`... :smile:

**Comment by gfyoung** [comment]
Also, Travis is telling me that you introduced a `flake8` error at some point, so I pushed a commit to fix that.

**Comment by StevenBlack** [comment]
@gfyoung ya, I know, sorry for the hassle, I had to do it.

Expunging the .zip binaries from the repo reduced its size by about 85%, about 400 Mb.

**Comment by gfyoung** [comment]
@StevenBlack : Were you trying to remove its history from the `git` repository as well?

**Comment by StevenBlack** [comment]
@gfyoung yes.  Git doesn't diff binaries, which is why the repo grew so large, so quickly.  You can't remove a file and its past incarnations without also modifying history.  All the commits are there, as well as all the text-based files and their past versions, but the hashes are different now.

**Comment by gfyoung** [comment]
@StevenBlack : Yep, that's what I suspected.  Thanks for clarifying!

**Pull request merged**
