### PR TITLE
sub domains from: adsafeprotected.com|zeroredirect.com|amazon.com

### PR DESCRIPTION
**Pull request by dnmTX**
adsafeprotected.com -> tracking and analytics (just adding the missing once)
zeroredirect.com -> heck of a nasty malware (same as above)
amazon.com -> found this one and it's not on the lists,hopefully it won't break anything
! ALL domains are currently ACTIVE !

### CODE REVIEW

**Comment by dnmTX** [comment]
@StevenBlack  i also have question that is not related to this commit.Now that i forked your repo and in the feature you do changes to (your) it, will it automatically sync with mine or i have to do it manually?

**Comment by StevenBlack** [comment]
@dnmTX you need to initiate sync with origin manually....

If you create a new local branch, and make changes to your new branch, this is always easier.  

Because my updates and changes get pushed to `master` branch.  If your feature branch is named `master`, then when you sync `master` from origin you are going to have a bad time.

On the other hand if your changes are made to branch `myFeature` then you can sync `master` and you’ll always be fine.

**Comment by StevenBlack** [comment]
Merging.

**Comment by ScriptTiger** [comment]
@dnmTX, what is your process for enumerating subdomains?

**Comment by dnmTX** [comment]
@ScriptTiger  considering the fact that @StevenBlack,s lists is already added to @funilrys's **dead-hosts** and (not sure on this one but i hope it is) Steven using it before doing new "release" i simply perform nslookup and if the IP gets resolved it's counted as active.Even if it's not(the domain(s) in question),all of them would be filtered by the dead-hosts anyway.But if nslookup tells me that it can not even find such a domain i wouldn't even bother adding it.It's just a simple check before the major filtering.

**Comment by StevenBlack** [comment]
Hi @dnmTX this is not how this works.

Look, this repo is a collection of CURATED hosts files.  

I am absolutely not interested in any process that iterates subdomains and, based on the merest evidence that the host exists, submits hosts to my personal ad-hoc data file. 

I absolutely don't want to end up with a million item host file.  Forget it; I'm not going there.

**Comment by dnmTX** [comment]
Ok,i will not add more.You can remove the one i already added if you want. Never would've thought that this will become such e problem,all those domains are active therefore harmful.

**Comment by ScriptTiger** [comment]
@dnmTX, I know you are not intentionally doing anything careless and we certainly appreciate your dedication. We have discussed these issues before in https://github.com/StevenBlack/hosts/issues/412. @funilrys is aware of some of these limitations and is working hard to counteract them as best he can. @mitchellkrogza uses @funilrys's stuff with live traffic, some automation, and some manual curation, so it's a supplement to an already acceptable system.

Whether we keep your contributions or not is up to @StevenBlack, but either way I brought this up more in hopes to improve the community, including you, in the collaborative spirit of open source. It's everyone's responsibility to help each other here. And whether or not your contributions are valid or not, it's more the method than the product that is important here. If the methods are consistent, the product will inherently follow suit.

**Comment by funilrys** [comment]
Hello, world!

I do not want to continue #412 here as we may continue the discussion at #412 later one day, so this will be concise as it's may be needed.

# About PyFunceble and analog projects

As I said elsewhere - maybe not clearer - in a previous issue under dead-hosts, PyFunceble is great but not complete (yet ?). Indeed, if we are talking about world accessible domain(s), PyFunceble is great to check availability.

BUT as some (or most !?) domain(s) apply a continent or country restriction - and it's truer now with GPDR which forced some domain(s)/service(s) to block access from Europe - PyFunceble in its today version is incomplete as the result may differ from country to country and even from continent to continent.

A lot of work has been done but PyFunceble please keep in mind that PyFunceble is still in **beta**.

You can now understand that it's quasi-impossible to know if a domain has such method or not. That's why I'm working (in a private branch) on a version which I (try to) implement a mode for testing from different locations using methods mentioned by @ScriptTiger in #412 along with other...

# About those subdomains and this PR

May I ask are we sure that those subdomains are not present in the current infrastructure? 

But yes Steven @StevenBlack is right. This repository is not designed to "end with millions of entries". 

That is what makes this repository and we must applause Steven @StevenBlack for his awesome work and "curation" restriction which makes this repository one of the best on the internet :+1: 

# About fork synchronization

@dnmTX Please find in the following documentation about working with fork(s):

* https://help.github.com/articles/working-with-forks/ (summary)
* https://help.github.com/articles/syncing-a-fork/

# About dead-hosts and this repository

To be clear, https://github.com/dead-hosts/hosts_git_StevenBlack and this repository are not currently in use for the previously mentioned reason but are there for information and especially for finding `INVALID` domains (which is always true from now).

The `clean.list` from dead-hosts can be used but with attentiveness like the way Majkit do with https://github.com/dead-hosts?utf8=%E2%9C%93&q=Maj&type=&language= and https://github.com/MajkiIT/polish-ads-filter/. Indeed, he compares the results from dead-hosts (with attention) with the results of PyFunceble in Poland and I'm really surprised by his report which gave me some idea for future work.)

But, on the other side, using `clean.list` is not that "bad" (not applicable to this repository, I'm talking globally)...
Indeed, as we keep a track of all `INACTIVE` and `INVALID`domain for continuous testing, once my private branch will be merged to `dev` then `master`, they will be automatically retested with the new system like it is actually the case every 24 hours.

# As conlusion

* Applause to @StevenBlack for his awesome work :clap: :clap:
* Applause to @ScriptTiger for being so reactive and for the awesome contribution he provides to the security/scripting world along with this repository.
* Welcome to the Git and open source world/community to @dnmTX :+1: 

There is a lot to do to make the world a better and secure place.
 
@dnmTX: Still a lot to learn but you are on the right path :+1:

**Pull request merged**
