### PR TITLE
Added 1 website to the list

### PR DESCRIPTION
**Pull request by Saya47**
Hello I'm a noob!
I don't see any "porn" related lists on your "contact one of our hosts sources".
But even if there was, I wouldn't know how to contact them!

Also, I noticed that when you modify a large file, the raw.githubusercontent.com website does NOT show the new changes! It just loads the old file on the browser, but if you download the file, it's fine and the changes are there, does this happen to everybody else? I don't think it's my browser cache because I tried a different browser and also deleted my cache!

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thank you @Saya47!  Good find.

The file you edited is generative.  So its contents are re-created on each release.

That means your change is good, but it's in the wrong file.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Ping @sinfonietta, will you list this domain and its `www` subdomain?

**Comment by dnmTX** [comment]
@Sinfonietta:
`0.0.0.0 javla.tv`
`0.0.0.0 www.javla.tv`
👍

**Review by HenrySoftwareStudio — APPROVED** [review]

**Comment by dnmTX** [comment]
hosts

Another day.....another **TROLL** 🤔

**Comment by StevenBlack** [comment]
Thanks @Saya47 I apologize for the delay.  Unacceptable.

Merging!

**Comment by StevenBlack** [comment]
@Saya47 sorry this commit was to a generative file, which is a comment I made [on October 31st](https://github.com/StevenBlack/hosts/pull/1804#issuecomment-955796951). 🙄 I need a holiday.

Ping @sinfonietta...

**Pull request merged**
