### PR TITLE
paledega source added

### PR DESCRIPTION
**Pull request by paledega**
This pull request is fix of https://github.com/StevenBlack/hosts/pull/1604

I split some address. 

If you have any problem I can move to other list

### CODE REVIEW

**Comment by paledega** [comment]
https://gist.github.com/paledega/14039224debc2fd954b835cc2288ce57

**Comment by dnmTX** [comment]
Steve @StevenBlack just for the record i'm **ALL AGAINST** merging this !!!!
To say that the list is too aggressive will be understatement  👎 👎 👎

**Comment by paledega** [comment]
I can create more splited hosts. I problem for me. 

also I think this adresses are not agressive.

**Comment by StevenBlack** [comment]
I'm sorry @paledega I'm not merging a GitHub Gist that's 4-days old.

We only carry data from sources with established track records, with a verifiable history of curation and activity.  That's just how we roll, here.

Remind me in a year, and then we'll see.

Also we've never carried a Gist.  It's an interesting idea.  But how do people raise and track issues with a Gist?  An endless thread at the bottom of the Gist?  How is that supposed to work in practice?

Closing.

**Comment by StevenBlack** [comment]
Look, @paledega, I really don't want to be unkind, but seriously now.   C'mon!

**Pull request closed without merging**
