### PR TITLE
PlayStation Telemetry over API

### PR DESCRIPTION
**Pull request by DavidGarciaCat**
Just found these two entries when I checked my Pihole after playing on my PS

### CODE REVIEW

**Comment by DavidGarciaCat** [comment]
There's another entry ( `takedown.api.playstation.com` ) that I don't know if it should be also included.

**Comment by DavidGarciaCat** [comment]
There's another entry (`takedown.api.playstation.com`); I don't know if it should also be included.

**Comment by StevenBlack** [comment]
Thank you for this PR David @DavidGarciaCat!

About the third domain, if we aren't sure, then let's not.

Merging!

**Comment by DavidGarciaCat** [comment]
hey @StevenBlack 

I just realised the two new items were only added to the main `hosts` file, not the alternatives. I guess it makes sense, and then they are merged somehow, or shall I create a new update for them too?

Thanks, and sorry for the silly question

**Comment by StevenBlack** [comment]
David @DavidGarciaCat the new domains are merged into the repo, and are part of the data, but won't propagate until the next release when I'll build all our lists.

**Pull request merged**
