### PR TITLE
Clean up updateHostsFile.py

### PR DESCRIPTION
**Pull request by gfyoung**
<strike>Add to `updateHostFiles.py` the command from the batch file (`updateHostsWindows.bat`) to flush the DNS cache on Windows.</strike>

Also does a bunch of code-cleanup along the way.

### CODE REVIEW

**Comment by gfyoung** [comment]
@StevenBlack : If you have similar concerns to those in #287, I can remove the Windows command part and just submit the clean-up by itself.

**Comment by StevenBlack** [comment]
Hi @gfyoung thank you for being so persistent on this.  I apologize for not getting back to you sooner.

I'm trusting my gut-feeling on this: automating the Windows piece will potentially trigger an avalanche of marginally knowledgeable Windows users complaining the generator doesn't work.

So YES, please!  If you cull-away the Windows-specific stuff then I'm happy to merge!

I'm happy to say to Windows users, copy the file yourself, or use the existing `updateHostsWindows.bat` that's provided as a post-process to the mainline generation process.

**Comment by gfyoung** [comment]
@StevenBlack : Removed all Windows-related changes (and pulled in some clean-up from #287), so ready to merge if everything looks good.

**Comment by gfyoung** [comment]
@StevenBlack : I have a branch on my fork called <a href="https://github.com/gfyoung/hosts/tree/windows-experimental"> windows-experimental </a> which incorporates all of the changes I've made to make the `updateHostsFiles.py`.  I'm happy to maintain this, as I've found this to work quite well (at least on my machine).

If you have any interest in incorporating this into the main code-base (probably as a separate branch off `master`), let me know!

**Comment by gfyoung** [comment]
@StevenBlack : Removed all Windows-related changes (and pulled in some clean-up from #287), so ready to merge if everything looks good.

**Comment by StevenBlack** [comment]
Good!

**Pull request merged**
