### PR TITLE
Fix typos in readme.md

### PR DESCRIPTION
**Pull request by someonefamous**
This fixes a few typos in readme.md, as well as updating 2 places that incorrectly refer to the hosts file as a 'folder'.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @someonefamous, thanks for the contribution!

Can you please make these changes in the `readme_template.md` file?

See the hosts file generation process merges data into `readme_template.md` to re-create `readme.md` each time.

So merging your contribution doesn't actually fix anything.

If you apply these changes to `readme_template.md` I'm happy to merge it.

**Comment by someonefamous** [comment]
Sure, can do!

**Comment by someonefamous** [comment]
Submitted changes to readme template instead - the only one not in there was the 'sketch vs sketchy' error.

**Comment by StevenBlack** [comment]
This is done in #682.  Closing.

**Pull request closed without merging**
