### PR TITLE
cross-compatible sudo FIXED CI

### PR DESCRIPTION
**Pull request by FadeMind**
I just follow https://github.com/StevenBlack/hosts/pull/439. IMO should be merged fine now. 

@StevenBlack  tested in Linux. Working fine.

### CODE REVIEW

**Comment by funilrys** [comment]
I'm curious @FadeMind, Which Linux Distribution don't have `/usr/bin/sudo`?

**Comment by StevenBlack** [comment]
@FadeMind Travis is complaining because of lint checks...

**Comment by FadeMind** [comment]
@funilrys done with lastest commit. Thanks for hint.

**Comment by gfyoung** [comment]
@funilrys @FadeMind : Compare this PR to #439 .  What exactly is the difference?

**Comment by FadeMind** [comment]
@gfyoung  THIS trivial 
https://github.com/StevenBlack/hosts/pull/519/commits/ee411d82c9c00fffcc22a4c8a7496dd6304aaf3b

**Comment by StevenBlack** [comment]
@FadeMind @gfyoung This PR is good-to-go!

Tomacz @FadeMind can you please stand by?  I'm going to merge PR #520 first, and I'd rather put the merge conflict here, not there 😸.  Good?

**Comment by FadeMind** [comment]
@StevenBlack Sure!

**Comment by StevenBlack** [comment]
Merging!  Thanks Tomasz @FadeMind and @gfyoung!

**Pull request merged**
