### PR TITLE
Added .gitattributes to normalize CRLF hosts files

### PR DESCRIPTION
**Pull request by ScriptTiger**
Addresses the following issue:
"Linebreaks (CR+LF) for Windows-Users #370"
https://github.com/StevenBlack/hosts/issues/370

### CODE REVIEW

**Comment by rautamiekka** [comment]
That's one clever way to do it.

**Comment by ScriptTiger** [comment]
Makes it easier for Windows users to view it as well as submit PRs without getting loads of diffs every line ending. Since most devs here are Linux, the scripts don't really matter at this point. And any dev that is on Windows probably knows better anyway, so this wouldn't affect them.

**Comment by ScriptTiger** [comment]
Lol, I was just reading through the recent PR from gfyoung and he mentioned this exact thing with a diff to his PR while working on a different machine. I swear this was not a personal attack on him saying he should know better, I just realized he even said that.

**Comment by ScriptTiger** [comment]
This is just a quick reminder to @Tobias-B-Besemer that this PR is still open and I have not forgotten about my promise. I don't know if he was tracking on this, but I just wanted to make sure.

**Pull request closed without merging**
