### PR TITLE
Remove Badd Boyz Hosts

### PR DESCRIPTION
**Pull request by mitchellkrogza**

### CODE REVIEW

**Comment by Jezza-x3** [comment]
Just wondering why?

**Comment by StevenBlack** [comment]
Badd-Boyz is a good list with exceptional curation activity that comes only from dedicated, conscientious oversight that I wish all lists would possess.

So, no.

Closing.   😄

**Comment by rautamiekka** [comment]
^ That makes no sense.

**Comment by mitchellkrogza** [comment]
Sorry, @StevenBlack @rautamiekka @Jezza-x3  some guy really irking me on https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues about my list having a "whole bunch" of incorrectly blocked domains but cannot seem to provide any evidence or contribute anything valuable. 

Probably just trying to wind me up and on a Saturday night when I'm relaxing I get easily wound up by guys trying to stir the pot. Thanks for trusting in me and my list, I work damn hard to make sure it's clean as can be.

**Pull request closed without merging**
