### PR TITLE
Add android instructions

### PR DESCRIPTION
**Pull request by FahadBinHussain**
Added instructions for how to setup and edit android `hosts` file

### CODE REVIEW

**Comment by Hackurei** [comment]
you don't need any magisk module to replace this file, you just need root access.
i believe this file is on a read only partition, so you just need to remount the partiton as read/write first.

also, the domain you provided is blocked by ublock origin:
blocked

**Comment by FahadBinHussain** [comment]
> you don't need any magisk module to replace this file, you just need root access. i believe this file is on a read only partition, so you just need to remount the partiton as read/write first.
> 
> also, the domain you provided is blocked by ublock origin: blocked

I don't know if remounting the partition as read/write would work or not. However, when I attempted to change the host file (the device was rooted), the changes were being made but the hosts were not being blocked. Additionally, I tried other methods to achieve this, but none of them were successful except for the Magisk module. Therefore, I thought it would be helpful for others to include that in the readme, as the Android instructions were also insufficient. As for the uBlock Origin domain block, that is merely a false positive.

**Comment by Lateralus138** [comment]
And note that root isn't even necessary to successfully get a hosts file to work on Android, a DNS client like NextDNS works perfectly fine and a lot simpler process. Not to mention the fact that less and less Android devices can be rooted nowadays and the average user doesn't or can't root their device.
Here's screenshots of 3 different browsers, one with 2 different links from Steven's main hosts file using NextDNS on Android:
android_with_hosts

**Comment by StevenBlack** [comment]
Thank you for this PR Fahad @FahadBinHussain, I appreciate the effort here.

Given the comments above ⬆️ I decline to include these changes.

Closing.

**Pull request closed without merging**
