### PR TITLE
Add source shady-hosts

### LINKED ISSUE #1491: My list of hosts
I found most of these through uMatrix. I usually avoid adding hosts that are already blocked in the other lists I use with uMatrix and uBO. I also usually avoid adding root domains, especially when they aren't serving scripts/images on third-party sites.

It isn't particularly large at the moment and it's also very new (I only recently realized I was finding enough of these to warrant making a separate list), but I'll try to consistently update it—time will tell.

- [List](https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts)
- [Repository](https://github.com/shreyasminocha/shady-hosts) — [History](https://github.com/shreyasminocha/shady-hosts/commits/main)
- [CC0-1.0](https://l.shreyasminocha.me/CC0-1.0/2020-)

```sh
❯ ghosts -c https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 58,750
Bytes: 1.8 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts
Domains: 135
Bytes: 4.0 kB
----------------------------------------
Intersection: 27 domains
```

Edit: moved repository and list to GitHub on dnmTX's suggestion.

### PR DESCRIPTION
**Pull request by shreyasminocha**
Resolves #1491

### CODE REVIEW

**Comment by dnmTX** [comment]
@shreyasminocha  just a suggestion but hosting your list her in GitHub will make it much easier and convenient if there is a  issue/false positive to be addressed/resolved in a timely matter. 
Most of the users don't even bother writing emails and just venting their frustration here.

**Comment by StevenBlack** [comment]
Thank you Shreyas @shreyasminocha!

Merging.

**Comment by StevenBlack** [comment]
Shreyas @shreyasminocha welcome aboard!

**Comment by dnmTX** [comment]
Steve @StevenBlack can you run `ghosts` for duplicates. Just in case cause i think i saw some so probably now it's the time for 
@shreyasminocha to remove them. Thanks 👍

**Comment by StevenBlack** [comment]
Hi Dan @dnmTX there are a few duplicates, as mentioned in Issue #1491.

I'm OK with the dups since the software filters them out...

**Comment by dnmTX** [comment]
Got it  and **Happy New Year** to **ALL** (hopefully a **better one** 🤞 )

**Pull request merged**
