### PR TITLE
What-Zit-Tooya-Ad-Block

### PR DESCRIPTION
**Pull request by FadeMind**
CC  @What-Zit-Tooya

@StevenBlack please review and merge if you like. 

Homepage: https://github.com/What-Zit-Tooya/Ad-Block

### CODE REVIEW

**Comment by dnmTX** [comment]
**WTF ??????**

Ad-Block

**Comment by FadeMind** [comment]
I ping maintainer, maybe he response 😉  @dnmTX

**Comment by dnmTX** [comment]
He is using VPN to block IP's.That's why bunch of them are present in his hosts list:
vpn

And also this(front page):
new

....so i'd say......HARD NOPE 👎

**Comment by What-Zit-Tooya** [comment]
> 
> 
> He is using VPN on his phone to block IP's.That's why bunch of them are present in his hosts list:
> vpn
> 
> And also this(front page):
> new
> 

That IPs from CNAME adservers address from Adguard log.

> 
> 
> 
> ....so i'd say......HARD NOPE 👎

Im using hosts that i need, analyze it and block it, if it wrong, i remove it.
Only using what i need.
Nah. im still n00b in this filter, still learning.

**Comment by StevenBlack** [comment]
Looking at this broadly,

```
$ ghosts -c https://raw.githubusercontent.com/What-Zit-Tooya/Ad-Block/main/Main-Blocklist/Ad-Block-HOSTS.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 81,745
Bytes: 2.5 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/What-Zit-Tooya/Ad-Block/main/Main-Blocklist/Ad-Block-HOSTS.txt
Domains: 1,671
Bytes: 54 kB
----------------------------------------
Intersection: 183 domains
```

**Comment by FadeMind** [comment]
@dnmTX @StevenBlack  https://github.com/What-Zit-Tooya/Ad-Block/commit/ab0155d9b9e8783c9af781dc1bebbba48a164773

**Comment by dnmTX** [comment]
Up to Steve @StevenBlack  ¯\_(ツ)_/¯
That kid's attitude...not really lines up to be close to a responsible lists curator. In my opinion.

**Comment by FadeMind** [comment]
I pushed latest changes in hosts from @What-Zit-Tooya in this PR. No more IPs directly in hosts. Only domains.

**Pull request closed without merging**
