### PR TITLE
Add purpleads.io

### PR DESCRIPTION
**Pull request by bigdargon**
The advertising domain is not in any source yet.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @bigdargon `purpleads.io` appears to be a company home page.  Are they serving ads from their root domain?

We aren't in the business of taking companies off the internet, nor do we need to restric people's access to those companies.  

We just want to block ads, tracking, and malware.  Not individuals or businesses.

**Comment by bigdargon** [comment]
The page I found an advertiser was serving ads `saoteen.net`

```

https://www.saoteen.net/2020/08/ap-e-thi-tieng-anh-tot-nghiep-thpt-quoc.html

```

And the site loads the script code

```
https://cdn.purpleads.io/load.js?publisherId=c89d4815b48148b0c6841b7c81c949c2:2b892fa4d1478d119ddd32147b73a274f8787387e3c1bcc272ab429dd602f008044f0813589f1f3bcfb2508c65836ea6c069f5aa8349a53f95d48f59d25ca310
```

In the script that contains the domain name to load

```
creatives.purpleads.io
api.purpleads.io
```


If you access the website from your phone (without ad filter) only using the domain blocker will show the ad

image

**Comment by dnmTX** [comment]
**CONFIRMED** 👍  but in my opinion it's more suitable to be added to [hostsVN](https://github.com/bigdargon/hostsVN)
**PING** @bigdargon

**Comment by bigdargon** [comment]
@dnmTX Thank you!  Because this domain has a server outside of Vietnam, so I added my resource but it is not a file for vietnamese server.

https://github.com/bigdargon/hostsVN/blob/752e0cb37ced2a9b882fc2d95b9e7e674c000b3c/hosts#L14626

In addition, this domain name seems to be less popular in newspapers in Vietnam. 😉

**Comment by llacb47** [comment]
> in my opinion it's more suitable to be added to [hostsVN](https://github.com/bigdargon/hostsVN)

It's already in Easylist (not a Vietnamese list) https://github.com/easylist/easylist/blob/5c88e57155f6d5882f6318a462bf4e3a312c0502/easylist/easylist_adservers.txt#L6624

`https://publicwww.com/websites/%22purpleads.io%22/`

**Comment by dnmTX** [comment]
Oh,i see now. It's not geo targeted.
@bigdargon  you can edit your PR to add the proper domains:
`0.0.0.0 creatives.purpleads.io`
`0.0.0.0 api.purpleads.io`
`0.0.0.0 cdn.purpleads.io`
....and the rest is up to Steve @StevenBlack

**Comment by bigdargon** [comment]
Thanks @dnmTX & @llacb47 !

**Comment by StevenBlack** [comment]
Thanks everybody!

Merging.

**Pull request merged**
