### PR TITLE
Encoding (#520) review

### PR DESCRIPTION
**Pull request by funilrys**
Hello everybody, 
I hope that everybody goes right out here!

First of all sorry for forcing this review after being so bad in #520 as I probably could write the following commits along with #520. 

Secondly **thanks to** @FadeMind for #526 which forced me to rewrite my previously submitted function in order to pass more tests. 
@FadeMind **your PR is great** but it does not resolve all the issue behind what you discovered as if we apply your patch, another issue can appear and can take us into a never-ending loop of fixing the same thing. 
The explanation behind that is that **I was dumb** when writing that line you changed. Indeed, if we reverse the list today, tomorrow we will still have to reverse it once more to fill a case like the one I mentioned: 

```
0.0.0.0(tabulations)domain(spaces & tabulations)# comments`
```
**I'm really sorry if I offended you and anyone else. I did not mean to offend anyone. My apologies if I did.**

Finally to explain the issue discovered by @FadeMind 
I'll invite you to download [ŧhis file](https://raw.githubusercontent.com/StevenBlack/hosts/318389b08f122ca6863e12f11f9771a3cd3bd09d/testUpdateHostsFile.py) and test it against the latest `updateHostsFile.py` ([cf](https://github.com/StevenBlack/hosts/tree/v1.1.0)) to understand what changed.

If you do not have time for that the discovered issue is the following:

If we have a line which looks like the following
```
0.0.0.0(space)domain(tabulation(s) and spaces)# comments
```
We got an issue because **I did not considerate that a tabulation can be after the domain**. Which is why I say that **#526 is not bad** as **the reversion solves the problem by splitting space before the tabulation**.

To resolve that I first **includes new tests to pass**.
Then instead of splitting directly according to a list reading order, I decided to **search which one of tabs or space comes first** in the string with (https://github.com/StevenBlack/hosts/commit/8405f87edb6a1fb9346409daaf5aee39b565355f#diff-0e14783994b4ea380231d48b421ae128R1165):

```
        tabs_position, space_position = (line.find(tabs), line.find(space))

        if tabs_position > -1 and space_position > -1:
            if space_position < tabs_position:
                separator = space
            else:
                separator = tabs
        elif not tabs_position == -1:
            separator = tabs
        elif not space_position == -1:
            separator = space
        else:
            separator = ''
```

In between, I discovered an issue which is: once we split if we have multiple occurrences of the separator (tabs or space) **we were not capable of converting it**. So I fixed that part by introducing a pseudo-index search with(https://github.com/StevenBlack/hosts/commit/8405f87edb6a1fb9346409daaf5aee39b565355f#diff-0e14783994b4ea380231d48b421ae128R1182):

```
            index = 1
            while index < len(splited_line):
                if splited_line[index]:
                    break
                index += 1
```

The rest stay almost the same.

Cheers,
Nissar.

### CODE REVIEW

**Comment by FadeMind** [comment]
@funilrys working fine...
```
[fademind@manjaro 00-HSTS.EXT]$ python3 updateHostsFile.py -a
Updating source data/add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source data/someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source data/CoinBlockerLists from https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser
Updating source data/adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source data/tyzbit from https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts
Updating source data/hpHosts-FSA from https://hosts-file.net/fsa.txt
Updating source data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source data/add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source data/UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
Updating source data/mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source data/hpHosts-ATS from https://hosts-file.net/ad_servers.txt
Updating source data/hpHosts-HFS from https://hosts-file.net/hfs.txt
Updating source data/hpHosts-PUP from https://hosts-file.net/pup.txt
Updating source data/add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source data/hpHosts-EMD from https://hosts-file.net/emd.txt
Updating source data/yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source data/hpHosts-MMT from https://hosts-file.net/mmt.txt
Updating source data/hpHosts-PSH from https://hosts-file.net/psh.txt
Updating source data/KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source data/Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source data/hpHosts-GRM from https://hosts-file.net/grm.txt
Updating source data/hpHosts-EXP from https://hosts-file.net/exp.txt
Updating source data/malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source data/Spotify-Ad-free from https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotifynulled.txt
Updating source data/CoinBlockerList from https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser
Updating source data/hpHosts-HJK from https://hosts-file.net/hjk.txt
Updating source data/add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
==>0.0.0.0 130.211.230.53<==
==>0.0.0.0 12.170.116.68<==
==>0.0.0.0 164.109.51.67<==
==>0.0.0.0 5.100.249.215<==
==>0.0.0.0 74.112.173.77<==
==>0.0.0.0 91.205.157.38<==
==>0.0.0.0 91.212.132.230<==
Success! The hosts file has been saved in folder 
It contains 751,067 unique entries.
```

Regards

**Comment by funilrys** [comment]
Hey @StevenBlack as the tests are marked as `errored` - which means that it's a Travis CI issue - can you restart them?

**Comment by StevenBlack** [comment]
@funilrys it's not clear how to restart tests.  Apparently closing and re-opening the issue restarts tests.

**Comment by StevenBlack** [comment]
That's great Nissar @funilrys!

**Comment by funilrys** [comment]
Thanks Steven @StevenBlack :tada: 

P.S: In the future if you go to the tests page for example https://travis-ci.org/StevenBlack/hosts/builds/348994868?utm_source=github_status&utm_medium=notification you normally also have a restart test button :+1:

**Comment by StevenBlack** [comment]
... if Flash is enabled.  That's never going to happen on any of my machines 😄

**Pull request merged**
