### PR TITLE
remove go.dhs.gov to utilizie dhs.gov shortened URLs

### PR DESCRIPTION
**Pull request by HHuckleberry**

### CODE REVIEW

**Comment by iam-py-test** [comment]
This is from Peter Lowe's list: https://pgl.yoyo.org/adservers/details.php?hostname=go.dhs.gov
go.dhs.gov is a redirect tracker, therefor, (in my opinion) it is correctly blocked. You are free to unblock it if you understand the risk.
Thank you.

**Comment by HHuckleberry** [comment]
make sure bitly gets blocked then. https://bitly.com/blog/tracking-link/

**Comment by iam-py-test** [comment]
That was just my opinion, not @StevenBlack's policy.
@pgl what do you think about bitly?
Thanks

**Comment by pgl** [comment]
> That was just my opinion, not @StevenBlack's policy. @pgl what do you think about bitly? Thanks

`bit.ly` is known as a URL shortener and people go there specifically to shorten URLs. `go.dhs.gov` is an internal link tracker that the DHS use, not for shortening links but just to track clicks.

I'm open to being convinced otherwise, but I feel that those are their primary purposes so that's why the entries are or aren't in my list.

**Comment by iam-py-test** [comment]
Sorry for pinging you, then.

**Comment by pgl** [comment]
> Sorry for pinging you, then.

Oh hey, no problem at all! Ping me any time.

**Comment by StevenBlack** [comment]
Thank you for this pull request Tim @HHuckleberry.

I decline to merge it for reasons explained above ⬆️.

Closing.

**Comment by HHuckleberry** [comment]
> > That was just my opinion, not @StevenBlack's policy. @pgl what do you think about bitly? Thanks
> 
> `bit.ly` is known as a URL shortener and people go there specifically to shorten URLs. `go.dhs.gov` is an internal link tracker that the DHS use, not for shortening links but just to track clicks.
> 
> I'm open to being convinced otherwise, but I feel that those are their primary purposes so that's why the entries are or aren't in my list.

go.DHS.gov is a URL shortener that lets DHS employees and contractors create short .gov URLs from official government domains, such as .gov, .mil, .fed.us, .si.edu, or state.xx.us URLs.  While DHS uses this for tracking, its not its sole purpose. When you use go.dhs.gov, you can trust that it is not malicious. 

With Bitly, I can create a bit.ly shortened URL and that use that link for tracking purposes. reference https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiz3prnk56CAxWZITQIHfdIB98QFnoECBQQAw&url=https%3A%2F%2Fbitly.com%2Fblog%2Fbest-link-trackers%2F&usg=AOvVaw1DwX7zI5dpGI4B9kaBX0z6&opi=89978449

The difference I see from a bit.ly link and a go.dhs.gov link, is i can trust where the go.dhs.gov link is taking me.

**Comment by pgl** [comment]
@HHuckleberry I'd argue that the *primary* use of `go.dhs.gov` absolutely is for tracking. The main page shows a list of the "top 25", lists stats on how many total clicks have been made, etc. Very few of those URLs really need shortening.

For Bitly, that's what it's known for - URL shortening. That's why people go to the site usually, to shorten a URL. It's integrated into all sorts of services as a URL shortener. etc. It does have tracking but that's not how (most) people think of the service.

Last thing, Bitly has threat protection of its own. I can't vouch for its effectiveness, but I've quite often seen `bit.ly` links that no longer work because they've been removed. They have some details about this here: https://bitly.com/blog/trust-safety-abuse-system/. `go.dhs.gov` is open to all government employees - and there are plenty of `.gov` sites which have hosted malicious content before.

This is all about threat protection though, the primary purposes of each site are what I'm really concerned about.

**Comment by goproslowyo** [comment]
> > > That was just my opinion, not @StevenBlack's policy. @pgl what do you think about bitly? Thanks
> > 
> > 
> > `bit.ly` is known as a URL shortener and people go there specifically to shorten URLs. `go.dhs.gov` is an internal link tracker that the DHS use, not for shortening links but just to track clicks.
> > I'm open to being convinced otherwise, but I feel that those are their primary purposes so that's why the entries are or aren't in my list.
> 
> go.DHS.gov is a URL shortener that lets DHS employees and contractors create short .gov URLs from official government domains, such as .gov, .mil, .fed.us, .si.edu, or state.xx.us URLs. While DHS uses this for tracking, its not its sole purpose. When you use go.dhs.gov, you can trust that it is not malicious.
> 
> With Bitly, I can create a bit.ly shortened URL and that use that link for tracking purposes. reference [bitly.com/blog/best-link-trackers](https://bitly.com/blog/best-link-trackers/)
> 
> The difference I see from a bit.ly link and a go.dhs.gov link, is i can trust where the go.dhs.gov link is taking me.

@HHuckleberry I have to comment here that it seems that these folks are not familiar with internal URL shorteners and are again arbitrarily enforcing their _opinions_ on what should and shouldn't be blocked and have lost sight of what the word "curated" actually means.

image

All too common in this repository as of late (more examples in #2514 #2515 #2516 #2517).

**Comment by StevenBlack** [comment]
@pgl please ignore this troll. This Anon GitHub user is not a contributor here, not an issue raiser here, not a supporter here, and appears to believe OSS owes him.

Dude, @goproslowyo, you're gone.

**Comment by dillonkirsch** [comment]
@goproslowyo appears to be trying to help. So while he may not be a regular contributor he appears to be trying to make a suggestion to make this list better. but instead of replying to his comment and supporting pull requests you just attacked him. goproslowyo appears to criticize individuals for their lack of understanding of internal URL shorteners and accuses them of imposing personal biases on blocking policies and provided 4 pull requests to back up his point.  Why did you go off on goproslowyo instead explaining why he is wrong? How is he supposed to raise concerns? Is there a better place to make suggestions to make this block list better? I feel like his concerns are legit.

**Pull request closed without merging**
