### PR TITLE
Add unittests for updateHostsFile.py

### PR DESCRIPTION
**Pull request by gfyoung**
Been sometime since I last contributed!

This PR adds a whole suite of tests for `updateHostsFile.py`.  I tested as much as I could, though the lack of modularity in the script made some functions hard to test.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Well, how cool is that?  Thank you @gfyoung!  I dig this.  

May I ask for one more thing?  Can you document this test suite, however briefly, in [readme_template.md](https://github.com/StevenBlack/hosts/blob/master/readme_template.md)?

**Comment by gfyoung** [comment]
@StevenBlack : Sure thing.  Quick question : these tests use the `nosetests` paradigm, though apparently the cool thing is to use `pytest`.  Any preferences?  `nosetests` was easier to setup, but I could move it to `pytest` (in another PR of course) if there's a preference.

**Comment by StevenBlack** [comment]
@gfyoung no preference here.  I suppose my standard answer should be, which of the two methods has the brighter future, in your view?

Several things about [updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) bother me, so if this means revisiting its structure to make it more testable, I'm pumped.

**Comment by gfyoung** [comment]
@StevenBlack : The current trend is moving away from `nosetests` and `unittest` towards `pytest`.  `pytest` does help to simplify testing and provides a lot of useful decorators for testing.  That being said, I'm hesitant about how well it would do on tests like these that very much rely on mocking a lot of different system and architecture-level checks so that we can cover a lot of ground.

I'll certainly give it a shot, and if it does help to make the tests cleaner, then sure, but I'll leave that for another time.  I'd like to look at the structure of `updateHostsFile.py` first before I revisit this.  Also, the regex should be vetted (especially in light of recent changes, which prompted me to write this) to make sure it properly matches to the domains and host file entries that we intend.

**Comment by StevenBlack** [comment]
I agree with everything above.

[UpdateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) started as a simple naïve merge-and-deduplication of several hosts files.  Then contributions came from every corner, and features got added, one-at-a-time.  

As they say, *sooner or later you WILL do a proper requirements analysis*.  But in many cases, this included, life comes at you fast.  New ideas and features appear opportunistically, so evolution is  organic. 

So introducing testing provides impetus to do it right.

**Comment by gfyoung** [comment]
@StevenBlack : For reference, there is some logic behind the trend:

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership." (from main page <a href="https://nose.readthedocs.io/en/latest/">here</a>).

Thus, there is some motivation to try to write it using alternatives like `nose2` and `pytest` (or just plain `unittest`), though the latter seems to have gained traction.

**Comment by gfyoung** [comment]
@StevenBlack : `readme_template.md` content has been added.  Ready to merge if there's nothing else.

**Comment by StevenBlack** [comment]
@gfyoung when I use `python` as it says in the docs, I get the following.

    $ python testUpdateHostsFile.py
    Traceback (most recent call last):
      File "testUpdateHostsFile.py", line 28, in <module>
        import mock
    ImportError: No module named mock

However I get this when I use Python 3, so it works under Python 3.

    $ python3 testUpdateHostsFile.py
    ...................................................
    ----------------------------------------------------------------------
    Ran 51 tests in 0.017s

Do we have a Python 3 constraint here?

**Comment by gfyoung** [comment]
@StevenBlack : Oops.  Need to add that to the documentation.  Just run

~~~
pip install mock
~~~

Then the tests will run fine (note: I run tests both on Python 2 and 3 on Travis).

**Comment by StevenBlack** [comment]
`pip install mock` works fine, but thereafter I get the same error.

    $ python testUpdateHostsFile.py
    Traceback (most recent call last):
      File "testUpdateHostsFile.py", line 28, in <module>
        import mock
    ImportError: No module named mock

Which makes no intrinsic sense.  However, that's what I get.

**Comment by gfyoung** [comment]
@StevenBlack : Are you sure you're pointing at the right `pip` ?

**Comment by StevenBlack** [comment]
@gfyoung     

    $ which pip
    /usr/local/bin/pip

**Comment by gfyoung** [comment]
@StevenBlack : Try `pip --version`

**Comment by StevenBlack** [comment]
@gfyoung 

    $ pip --version
    pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by gfyoung** [comment]
Can you go into `site-packages` and see if there is `mock` package installed?

Also, can you try `python -V` ?

**Comment by gfyoung** [comment]
@StevenBlack : Added instructions for installing `mock` in the README.  Let me know if you can resolve your installation issues on your own machine.  Otherwise, this should be good to merge.

**Comment by StevenBlack** [comment]
@gfyoung it installed and ran on my secondary Mac.  

Seems OK, though I did get the following tree errors under Mac OS latest.

    $ python testUpdateHostsFile.py
    ...........................................E..EE...
    ======================================================================
    ERROR: test_no_isatty (__main__.TestSupportsColor)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "testUpdateHostsFile.py", line 709, in test_no_isatty
        with self.mock_property("sys.stdout.isatty") as obj:
      File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1460, in __enter__
        setattr(self.target, self.attribute, new_attr)
    AttributeError: 'file' object attribute 'isatty' is read-only

    ======================================================================
    ERROR: test_posix (__main__.TestSupportsColor)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "testUpdateHostsFile.py", line 668, in test_posix
        with self.mock_property("sys.stdout.isatty") as obj:
      File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1460, in __enter__
        setattr(self.target, self.attribute, new_attr)
    AttributeError: 'file' object attribute 'isatty' is read-only

    ======================================================================
    ERROR: test_windows_ansicon (__main__.TestSupportsColor)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "testUpdateHostsFile.py", line 693, in test_windows_ansicon
        with self.mock_property("sys.stdout.isatty") as obj:
      File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1460, in __enter__
        setattr(self.target, self.attribute, new_attr)
    AttributeError: 'file' object attribute 'isatty' is read-only

    ----------------------------------------------------------------------
    Ran 51 tests in 0.016s

**Comment by gfyoung** [comment]
@StevenBlack : Ah, this is good to know.  Maybe we need to add an OSX build on Travis.

**Comment by gfyoung** [comment]
@StevenBlack : Hmm...I guess my work is needed before OSX can be added.  Will work out in a follow-up.

**Comment by StevenBlack** [comment]
@gfyoung Thanks.  I applied aab02b and I still see those three errors.

It feels close though!  Thanks for taking care of this.

**Comment by gfyoung** [comment]
@StevenBlack : The commit was to add OSX to Travis.  I actually didn't do anything code-wise.

**Comment by gfyoung** [comment]
@StevenBlack : Could you pull down my branch again and give it a shot?

**Comment by StevenBlack** [comment]
Beauty!

Merging 😎

**Comment by gfyoung** [comment]
@StevenBlack : Thanks!  As an immediate follow-up, will attempt to load OSX onto Travis.

**Pull request merged**
