### PR TITLE
Adding updatefaker.com

### PR DESCRIPTION
**Pull request by borisschapira**
Prank site that makes you believe your computer is updating

### CODE REVIEW

**Comment by StevenBlack** [comment]
Merci Boris @borisschapira.

Je ne suis pas convaincu que ce site est malicieux.

@everyone: does anybody feel updatefaker.com is malicious?

**Comment by FadeMind** [comment]
It is not dangerous. It's funny. It's like blocking the MAZE game because you feel shock.

**Comment by borisschapira** [comment]
I had in mind rather to avoid panic among the people targeted by these kinds of jokes, but I understand your reluctance.

**Comment by spirillen** [comment]
I agree with @FadeMind on this :)  Just happy they haven't learned about *nix :yum:

**Comment by StevenBlack** [comment]
Thanks, everybody.  Merci Boris @borisschapira.

**Pull request closed without merging**
