### PR TITLE
add disable-dnscache-service-win.cmd

### PR DESCRIPTION
**Pull request by FadeMind**
@StevenBlack  

DNSCache service in Windows can **hang** network when you use bigger hosts file. Hard workaround is forcing disable service via registry tweak. Windows 10 have new security and you cannot just using `services.msc` easly. 

Reference:
- https://docs.microsoft.com/en-us/answers/questions/47441/how-to-disable-windows-10-dns-cache-services.html
- https://docs.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/disable-dns-client-side-caching

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thanks Tomasz @FadeMind this is good, I like it.

Can you amend this PR to document `disable-dnscache-service-win.cmd` in the [readme_template.md](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) file?  Perhaps in the [Updating hosts file on Windows](https://github.com/StevenBlack/hosts) section, or in its own section just below.  Are you comfortable with that?

The `hosts` file size has been creeping upwards in the past few months.  Are we in *bigger hosts file* territory now, where problems on Windows are occurring?

**Comment by FadeMind** [comment]
@StevenBlack 


Your original hosts file have 79 299 entries. 2,15 MB
My custom have 82 719 entries. 2,27 MB

Don't know where is border. For recover I had to using Manjaro ISO for replacing backup file 😁

**Comment by StevenBlack** [comment]
Thanks Tomasz @FadeMind.  This is great.

I may modify the new docs a little, but this is awesome and thank you for making this.

Merging!

**Comment by dnmTX** [comment]
> Your original hosts file have 79 299 entries. 2,15 MB
My custom have 82 719 entries. 2,27 MB

Just did little research and found that max hosts file size is 135 KB = 0.005 MB....

> Are we in "bigger hosts file" territory now

**you exceeded the the maximum size allowed** 😄

**Pull request merged**
