### PR TITLE
Removing my contribution

### PR DESCRIPTION
**Pull request by xetorixik**
As discussed over here: https://github.com/StevenBlack/hosts/issues/881
I can not and will not contribute in view of these circumstances. 
Therefore the request for the removal of my contribution.
Thanks.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Not merging this.

**Comment by xetorixik** [comment]
Because?

**Comment by StevenBlack** [comment]
This is my ad-hoc file.  I curate it.  And this is my repo.  I manage it.

My name is Steve Black, what's yours, anonymous troll?

**Comment by xetorixik** [comment]
What happened to you?

If I make a contribution, I'll be thanked and if you don't like it, 
I'm suddenly an anonymous troll?

**Comment by DPTJKKVH** [comment]
@StevenBlack look at our accounts we are not the same person. If I was I would request the removal of my contribution as well. And what is with all the name flexing?! People who care for privacy tend to not register with their real name. So zip up your pants, you are embarrassing yourself.

You should take a deep breath and realize that you are not trolled but simply pissed off a couple of people who formerly helped you in one way or another. You are not a victim. You just made decisions that some people do not want to be associated with. That is all.

**Comment by xetorixik** [comment]
I can advise anyone to remove their contribution and not to use this list anymore.

If everything goes well, Steven is satisfied and if you deviate, he becomes angry just like a child.
I'm out of here. Have a lot of fun. Bye Bye.

**Comment by StevenBlack** [comment]
So we're clear: Daniel @lightswitch05 requested removal of his personally-curated data source from this repo, and I merged his PR to execute that.

**Comment by xetorixik** [comment]
@StevenBlack .......so maybe you can also grant my request. Thanks.

**Comment by rautamiekka** [comment]
What a sad day ...

**Comment by funilrys** [comment]
I'm not taking the defense of anybody in this but let's talk technically.

There is a difference between your request and @lightswitch05's request, @xetorixik.

@lightswitch05 lists and contribution were not directly into this repository. 
Indeed as you can see in the commits ([cf](https://github.com/StevenBlack/hosts/commit/6e1c186f5e52d5cf75fdc095c202aa9083e01aff)) - which produced the deletion of his lists - there was an `update.json` and a directory under `data`. Basically, that means that it was an input source. 

The system only pulls the data based on the content of `update.json` and distribute a hosts file with the upstream content. In that constellation, @lightswitch05 had all the rights over his list.

Your contribution on the other side was directly done under `data/StevenBlack/hosts` which means that you contributed to the list but `data/StevenBlack` which means @StevenBlack is the manager/maintainer of that list. He is the one who can tell what stay or not.

In other words: You contributed but as you don't manage/maintain the list and:
  * there is no contribution guidelines,
  * nor a Contributor License Agreement (CLA) ([for example the one I had to sign recently](https://adblockplus.org/eyeo-contributor-license-agreement.pdf)),
    * [More info about CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement)
  * nor a Code Of Conduct (COC) which may clarify such situation,

you may have lost the right to remove your contribution.

--------------------------------------

It is maybe time to create a new discussion about the necessity to clarify such a situation for the future.
What's your input on that Steve @StevenBlack?

Cheers,
Nissar

*Note: I'm not going to continue this discussion here if it is not constructive as not everybody will look at this, PR is not the place for discussion which is not related to the code directly and the discussion may escalate (again :cry: ). If you need my input please create a new issue or contact me personally.*

**Pull request closed without merging**
