### PR TITLE
ADD:osint.digitalside.it

### PR DESCRIPTION
**Pull request by FadeMind**
Reference: https://github.com/FadeMind/hosts.extras/issues/45

Homepage: https://github.com/davidonzo/Threat-Intel
```
DigitalSide Threat-Intel
This repository contains a set of Open Source Cyber Threat Intellegence information, 
mostly based on malware analysis and compromised URLs, IPs and domains.

The purpose of this project is to develop and test new wayes to hunt, analyze, 
collect and share relevants sets of IoCs to be used by SOC/CSIRT/CERT with minimun effort.
```
Hosts file have 2000+ entries. 
Please review and merge. Thanks. 
License: MIT > https://github.com/davidonzo/Threat-Intel/blob/master/LICENSE

CC @StevenBlack 
CC @davidonzo
CC @tscpd

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thanks Tomasz @FadeMind.

2,211 domains, with a 47-domain intersection with our main list.

```
$ ghosts -c https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt --intersection

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 55,481
Bytes: 1.7 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt
Domains: 2,211
Bytes: 58 kB
----------------------------------------
intersection: [aahnaturals.net avanttipisos.com.br bigtreestudios.org brandtodigital.com capasca.ga carlostendero.com cdn.gv-industries.co.uk cnaantours.co.il compactholidayclub.com dakwahwisata.net datacentertecnologia.com.br electronicsvibes.com elenaplescan.com handfinger.com hapyc.com hasznaltgumivetel.hu inmaainv.com interbus.cz invaluablearts.com iotforall.ru n-brake.com oghniyati.com pattayalife.net pellesbar.co.il proqualityodontologia.com.br pujashoppe.in pumppazh.com qualitychildcarepreschool.com removepctrojan.com renimin.mymom.info rockstarcbd.com ruralagricola.com.br ryner.net.au sayed.azq1.com sff3d.com shop.qihchina.com syracusecoffee.com thichdocu.com timothefernandezcreationmetal.com tldrnet.top u-post.top wikihookah.com www.breedenandsilver.com www.cupgel.com www.mycollegecp.com www.removepctrojan.com yakupabdal.com]
Intersection: 47 domains
```

**Comment by StevenBlack** [comment]
Idle-thoughts: `.com` heavy.  Very light on Asia.  Not a critique, just what the data says.

```
./ghosts --tld -m https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt
Domains: 2,211
Bytes: 58 kB
TLD tally:
   com: 1,118
   org: 72
   net: 61
   ru: 60
   in: 60
   br: 48
   ua: 43
   nl: 37
   de: 36
   fr: 31
   uk: 31
   it: 29
   by: 28
   ir: 26
   za: 24
   xn--p1ai: 23
   vn: 22
   mx: 17
   kz: 17
   cn: 16
   gr: 16
   co: 15
   au: 14
   pl: 14
   xyz: 12
   cl: 10
   biz: 10
   es: 10
   hu: 10
   lt: 10
   us: 9
   eu: 9
   ch: 8
   website: 7
   be: 7
   dk: 7
   top: 6
   info: 6
   tr: 6
   ga: 6
   online: 6
   ro: 6
   pe: 5
   at: 5
   id: 5
   ca: 5
   tz: 5
   club: 5
   pk: 4
   my: 4
   pt: 4
   ml: 4
   cz: 4
   ge: 4
   th: 4
   jp: 4
   il: 4
   site: 4
   uz: 4
   nz: 3
   shop: 3
   ke: 3
   ec: 3
   ng: 3
   su: 3
   bd: 3
   az: 3
   io: 3
   tv: 3
   md: 3
   ar: 3
   ph: 3
   np: 3
   edu: 2
   tk: 2
   lk: 2
   se: 2
   store: 2
   cc: 2
   zw: 2
   gq: 2
   sg: 2
   tw: 2
   sa: 2
   rs: 2
   ps: 2
   ovh: 2
   lu: 2
   pw: 2
   am: 2
   kg: 2
   asia: 2
   me: 2
   cloud: 2
   pro: 2
   app: 2
   sk: 1
   bi: 1
   education: 1
   tn: 1
   iq: 1
   monster: 1
   gallery: 1
   mm: 1
   works: 1
   fi: 1
   et: 1
   hr: 1
   black: 1
   company: 1
   xn--p1acf: 1
   kim: 1
   bh: 1
   tech: 1
   pictures: 1
   run: 1
   domains: 1
   dm: 1
   live: 1
   cat: 1
   zm: 1
   si: 1
   social: 1
   fun: 1
   cw: 1
   ug: 1
   space: 1
   no: 1
   al: 1
   health: 1
   mw: 1
   hamburg: 1
   ie: 1
   re: 1
   moscow: 1
   sv: 1
   mz: 1
   name: 1
   la: 1
   vip: 1
   nu: 1
   do: 1
----------------------------------------

```

**Comment by StevenBlack** [comment]
This is an excellent PR.  Thank you Tomasz @FadeMind, thank you Davide @davidonzo.

Merging.

**Comment by davidonzo** [comment]
Thanks to you @StevenBlack!

**Pull request merged**
