### PR TITLE
Re-Source and Update Tyzbit Hosts list

### PR DESCRIPTION
**Pull request by tyzbit**
Sourcing from a fork of this repo for my list was not the best approach for me to take.
To that end, I've created a gist to use as the base for my domain list.

**This includes additional domains from the previous list**

I've updated from the previous domain list to:
* remove old unresolvable domains (per the [dead-hosts](https://github.com/dead-hosts/hosts_git_tyzbit/tree/master/output/domains) list)
* add additional entries.

This list was compiled from two primary sources:

[Debloat Windows 10](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1#L19-L158)
[Windows Spy Blocker](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/win10/spy.txt)

This was originally proposed in #537, but the changes were reverted due to some confusion in #539 even though it appears the issue reported was actually desirable host-blocking functionality.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thanks @tyzbit!  Merging.

**Comment by dnmTX** [comment]
@tyzbit  the reason @StevenBlack  reverted in #539  was because he couldn't access MSN.com from his location,it was blocked by "a-0003.a-msedge.net" domain.Mine as well remove it from the list to avoid future complaints.

**Comment by tyzbit** [comment]
@StevenBlack should I proactively update my gist to remove that domain before we get complaints?

**Comment by StevenBlack** [comment]
@tyzbit yes please.  MSN's unreachable with latest.  Not that I personally object to that, mind you 😈

**Comment by tyzbit** [comment]
https://gist.github.com/tyzbit/83b3297cb8ce1e5af4c90d232b1f5886 has been updated

**Comment by StevenBlack** [comment]
@tyzbit [Done!](https://github.com/StevenBlack/hosts/releases/tag/v1.3.8).

**Comment by StevenBlack** [comment]
MSN works with [latest](https://github.com/StevenBlack/hosts/releases/tag/v1.3.8).  Thanks everybody!

**Pull request merged**
