### PR TITLE
Removed thepiratebay.* from blocked hosts

### PR DESCRIPTION
**Pull request by cvuser0**
I think they accidentally ended up in this list.
thepiratebay is not a website that will force itself on people if you don't block it, you only get involved with it if you willingly navigate to the website.
This website is symbolic for freedom of information and does not belong on a blacklist full of ads and malware serving hosts.

### CODE REVIEW

**Comment by cvuser0** [comment]
I'm aware of the whitelist feature, but i use these hosts files on my phone to block ads and malicious websites.
My phone does not offer a real good way to whitelist hosts except using nano in a terminal app to manually comment out all hosts i want to whitelist.
Besides, thepiratebay.* does not belong on this hosts blacklist.

**Comment by FadeMind** [comment]
@cvuser0 Since @StevenBlack  merged http://hosts-file.net/ host file  warez sites are blocked in default. 
See: http://hosts-file.net/default.asp?s=thepiratebay and: http://hosts-file.net/?s=classifications

all thepiratebay site are marked WRZ.

`WRZ - Sites engaged in the selling, distribution or provision of warez (including but not limited to keygens, serials etc), where such provisions do not contain malware`

Thats why better way is just simply customize hosts file via sed command (not whitelisting due https://github.com/StevenBlack/hosts/issues/57)/)

**Comment by cvuser0** [comment]
@FadeMind I don't agree with the classification WRZ, thepiratebay is a filesharing community that does not discriminate/filter based on what content.
The users are responsible for what they upload.
I once downloaded some cute cat pictures off the piratebay, is that downloading of warez or piracy? no.
[this is what i use it for (for example)](https://thepiratebay.se/torrent/7698662/Cute_Kitty_Cats)

**Comment by FadeMind** [comment]
@cvuser0 Simple: You want have access to some sites, customize your hosts file.

**Comment by cvuser0** [comment]
@FadeMind The problem is that using a terminal emulator on a small android phone is not the most elegant way to go, i thought that there may be more people loading these hosts files into their phones and that this was a way to help other people.

I understand that you won't unblock it, so i'll try and take it up with hosts-file.net.
I think that the classification WRZ does not fit the piratebay at all, thepiratebay is a filesharing website and it does not stimulate piracy or spreading of WRZ in any way.
thepiratebay only stores checksums for p2p filesharing which is completely legal and has nothing to do with warez

**Comment by StevenBlack** [comment]
I've just removed hosts-file.net as a data source in this repo.  

I've updated the readme to point to that file for those who want to include it in their own forks and clones.

Closing.

**Comment by fcore117** [comment]
piratebay still is blocked, with every update i have to remove it manually

**Comment by spirillen** [comment]
This output would lead to the question. Which of the `hosts` file are you subscribed to?

```
grep -Ri 'thepiratebay.'
hosts:0.0.0.0 thepiratebay-proxylist.se
hosts:0.0.0.0 thepiratebay.be
hosts:0.0.0.0 thepiratebay.bl
hosts:0.0.0.0 thepiratebay.cr
hosts:0.0.0.0 thepiratebay.is
hosts:0.0.0.0 thepiratebay.ki
hosts:0.0.0.0 thepiratebay.org
hosts:0.0.0.0 thepiratebay.wtf
hosts:0.0.0.0 www.thepiratebay.cr
hosts:0.0.0.0 www.thepiratebay.org
hosts:0.0.0.0 www.thepiratebay.wtf
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay-proxylist.se
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.be
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.bl
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.cr
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.is
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.ki
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.org
data/CoinBlockerList/hosts:0.0.0.0 thepiratebay.wtf
data/CoinBlockerList/hosts:0.0.0.0 www.thepiratebay.cr
data/CoinBlockerList/hosts:0.0.0.0 www.thepiratebay.org
data/CoinBlockerList/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-gambling-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-gambling-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-gambling-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-gambling-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-porn-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-porn-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-porn-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-porn-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/social/hosts:0.0.0.0 thepiratebay.be
alternates/social/hosts:0.0.0.0 thepiratebay.bl
alternates/social/hosts:0.0.0.0 thepiratebay.cr
alternates/social/hosts:0.0.0.0 thepiratebay.is
alternates/social/hosts:0.0.0.0 thepiratebay.ki
alternates/social/hosts:0.0.0.0 thepiratebay.org
alternates/social/hosts:0.0.0.0 thepiratebay.wtf
alternates/social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/social/hosts:0.0.0.0 www.thepiratebay.org
alternates/social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-gambling/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-gambling/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-gambling/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-gambling/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-porn/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-porn/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-porn/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-porn/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.be
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.bl
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.cr
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.is
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.ki
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.org
alternates/gambling-porn-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/gambling/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/gambling/hosts:0.0.0.0 thepiratebay.be
alternates/gambling/hosts:0.0.0.0 thepiratebay.bl
alternates/gambling/hosts:0.0.0.0 thepiratebay.cr
alternates/gambling/hosts:0.0.0.0 thepiratebay.is
alternates/gambling/hosts:0.0.0.0 thepiratebay.ki
alternates/gambling/hosts:0.0.0.0 thepiratebay.org
alternates/gambling/hosts:0.0.0.0 thepiratebay.wtf
alternates/gambling/hosts:0.0.0.0 www.thepiratebay.cr
alternates/gambling/hosts:0.0.0.0 www.thepiratebay.org
alternates/gambling/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-gambling-porn/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-gambling-porn/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-gambling-porn/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-gambling-porn/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/gambling-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.be
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.bl
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.cr
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.is
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.ki
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.org
alternates/gambling-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/gambling-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/gambling-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/gambling-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/porn-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/porn-social/hosts:0.0.0.0 thepiratebay.be
alternates/porn-social/hosts:0.0.0.0 thepiratebay.bl
alternates/porn-social/hosts:0.0.0.0 thepiratebay.cr
alternates/porn-social/hosts:0.0.0.0 thepiratebay.is
alternates/porn-social/hosts:0.0.0.0 thepiratebay.ki
alternates/porn-social/hosts:0.0.0.0 thepiratebay.org
alternates/porn-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/porn-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/porn-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/porn-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.be
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.bl
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.cr
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.is
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.ki
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.org
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 thepiratebay.wtf
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.cr
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.org
alternates/fakenews-gambling-porn-social/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/porn/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/porn/hosts:0.0.0.0 thepiratebay.be
alternates/porn/hosts:0.0.0.0 thepiratebay.bl
alternates/porn/hosts:0.0.0.0 thepiratebay.cr
alternates/porn/hosts:0.0.0.0 thepiratebay.is
alternates/porn/hosts:0.0.0.0 thepiratebay.ki
alternates/porn/hosts:0.0.0.0 thepiratebay.org
alternates/porn/hosts:0.0.0.0 thepiratebay.wtf
alternates/porn/hosts:0.0.0.0 www.thepiratebay.cr
alternates/porn/hosts:0.0.0.0 www.thepiratebay.org
alternates/porn/hosts:0.0.0.0 www.thepiratebay.wtf
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay-proxylist.se
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.be
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.bl
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.cr
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.is
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.ki
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.org
alternates/gambling-porn/hosts:0.0.0.0 thepiratebay.wtf
alternates/gambling-porn/hosts:0.0.0.0 www.thepiratebay.cr
alternates/gambling-porn/hosts:0.0.0.0 www.thepiratebay.org
alternates/gambling-porn/hosts:0.0.0.0 www.thepiratebay.wtf
```

And from the git blame
```
git blame -sw hosts | grep 'thepiratebay.'
aba3723b9 35005) 0.0.0.0 thepiratebay-proxylist.se
aba3723b9 35006) 0.0.0.0 thepiratebay.be
aba3723b9 35007) 0.0.0.0 thepiratebay.bl
aba3723b9 35008) 0.0.0.0 thepiratebay.cr
aba3723b9 35009) 0.0.0.0 thepiratebay.is
aba3723b9 35010) 0.0.0.0 thepiratebay.ki
aba3723b9 35011) 0.0.0.0 thepiratebay.org
aba3723b9 35012) 0.0.0.0 thepiratebay.wtf
aba3723b9 36236) 0.0.0.0 www.thepiratebay.cr
aba3723b9 36237) 0.0.0.0 www.thepiratebay.org
aba3723b9 36238) 0.0.0.0 www.thepiratebay.wtf
```
You'll see it was added with commit aba3723b9 

So my best adwise is to fork this repo, add the pirates to the whitelist, let Travis keep you own fork up to date, and then use that repo's hosts file on your phone

**Comment by fcore117** [comment]
I just remove manually, never messed with git and no time for that. Why do not t remove officially i dont understand. Until that manual is fine. I use simple .cmd file that replaces hosts when i descide to update.

**Pull request closed without merging**
