### PR TITLE
add an optional blacklist file

### PR DESCRIPTION
**Pull request by tomhoover**
The contents of this file (containing a listing of additional
domains in 'hosts' file format) are appended to the unified hosts
file during the update process.

### CODE REVIEW

**Comment by tomhoover** [comment]
I wanted the ability to add my own URLs (similar to https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts); however, adding a list to either `data/` or `extensions/` requires one to include an `update.json` file. Inspired by the simplicity of the local `whitelist`, I added the ability to create a local (optional) `blacklist`.

**Comment by FadeMind** [comment]
@tomhoover  see https://github.com/StevenBlack/hosts/blob/master/myhosts

and https://github.com/StevenBlack/hosts/commit/7934f87b41c58bdd38a99297038bcc492c5471ba

**Comment by StevenBlack** [comment]
Excellent!  Thank you very much this will definitely be merged.

Can I ask you to please make a couple of mods first?

First, can you rename `blacklist.example` to the actual name, in this case `blacklist`.  This will match the `whitelist` we already have.  Feel free to stuff comments in the `blacklist` as you see fit to explain its purpose.  Also please mod the docs for occurrences of `blacklist.example`.

Second, I get this error when running `updateHosts.py` on Python 2.7.   Is this new?

    Traceback (most recent call last):
      File "updatehostsfile.py", line 567, in <module>
        main()
      File "updatehostsfile.py", line 141, in main
        mergeFile = createInitialFile()
      File "updatehostsfile.py", line 296, in createInitialFile
        writeData(mergeFile, curFile.read())
      File "updatehostsfile.py", line 68, in writeData
        f.write(str(data).encode("UTF-8"))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3270: ordinal not in range(128)

**Comment by StevenBlack** [comment]
@FadeMind I kinda prefer `blacklist` to `myhosts`.   I'm leaning towards `myhosts` as the top-of-file default hosts.

@tomhoover's blacklist currently goes to bottom-of-file which is nice.

**Comment by StevenBlack** [comment]
@tomhoover ya the Python 2.7 crash upon `python updateHostsFile.py` is my bug, not yours.

**Comment by tomhoover** [comment]
@FadeMind, I realize the same thing could have been accomplished by adding the '0.0.0.0 blacklisted.com' entries into the `myhosts` file; however, I like to use `myhosts` as literally *my* hosts (I have the 192.168.x.x entries for my local computers in `myhosts`). I thought it cleaner for *my* hosts to remain at the top of the file, and additional *blacklisted* domains to appear at the bottom of the file. Hence, there was a method to my madness... 😄

**Comment by tomhoover** [comment]
@StevenBlack, I used the convention of `blacklist-example` based upon the comments re `myhosts` and `whitelist` in issue #144. (I assumed from reading #144 that `myhosts` and `whitelist` would soon be renamed to `myhosts-example` and `whitelist-example`.)

If renaming the other two files is not in the works, let me know and I'll go ahead and rename `blacklist-example` to `blacklist` (and update the docs) as you requested.

**Comment by StevenBlack** [comment]
Sorry @tomhoover I thought I was clear.

> First, can you rename blacklist.example to the actual name, in this case blacklist. This will match the whitelist we already have. Feel free to stuff comments in the blacklist as you see fit to explain its purpose. Also please mod the docs for occurrences of blacklist.example.

Thanks!

**Comment by tomhoover** [comment]
@StevenBlack, revised as requested.

**Comment by StevenBlack** [comment]
Beautiful!  Thanks Tom! @tomhoover

**Pull request merged**
