### PR TITLE
Update StevenBlack hosts

### PR DESCRIPTION
**Pull request by mullinsmikey**
Added several Samsung Smart TV taking part in distributing ads or collecting telemetry

### CODE REVIEW

**Comment by snowdenjohnch** [comment]
Hello,

I read this beatiful artilce https://forum.xda-developers.com/android/apps-games/warden-app-manager-t4122227 on XDA.

Can you add their list, you can find it  https://send.firefox.com/download/2d10064b197b304b/#WydxB9-2SmZLtfpfT2PnBw or in the previous link, in order to protect our smartphone from trackers?

Thanks for all!

**Comment by StevenBlack** [comment]
@snowdenjohnch please open a separate issue or pull request for that, since your suggestion is not related to this.

Michael @mullinsmikey this is a good PR.  Merging.  Thank you!

**Comment by snowdenjohnch** [comment]
Ok sorry, I'm new on github, I oper a new issue.

**Comment by mullinsmikey** [comment]
DW, guys. I can handle this too :)

**Pull request merged**
