### PR TITLE
Add URLHaus

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by dnmTX** [comment]
Looks promising. Checked few domains from the list in VirusTotal and they all had high detection.
@dimkr give time to Steven @StevenBlack to assess your request.
Are you the curator of the lists,or just passing out the info?
Either way,i think it will be a good addition here 👍

**Comment by StevenBlack** [comment]
The intersection set is 5 domains.

```
$ ./hoststools -c https://raw.githubusercontent.com/StevenBlack/hosts/4d295cc30fd7898491128b77dfe93bde56d11cea/data/URLHaus/hosts
--------------------------------------------------------------------------------
Base hosts file summary:
--------------------------------------------------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 51,985
Bytes: 1.6 MB
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Compared hosts file summary:
--------------------------------------------------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/4d295cc30fd7898491128b77dfe93bde56d11cea/data/URLHaus/hosts
Domains: 1,033
Bytes: 28 kB
--------------------------------------------------------------------------------
Intersection: 5 domains
```

**Comment by StevenBlack** [comment]
Dan @dnmTX and Dima @dimkr we've talked about URLHaus before.  See **Consider including URLhaus domains** which is Issue #1143.

I sent an email in February requesting permission, but received no reply.

The [CC0 license — “No Rights Reserved”](https://creativecommons.org/share-your-work/public-domain/cc0/) is nice.

Maybe we should just, do it.

**Comment by StevenBlack** [comment]
Dan @dnmTX is it actually weird the intersection set is just 5 domains?  That's 0.5% intersection.

URLHaus doesn't list anything from Google, nothing from Doubleclick... It's just, weird.

Your thoughts?

**Comment by dimkr** [comment]
> Are you the curator of the lists,or just passing out the info?

Just passing the info. I discovered this source today, after doing some research for a pet project that needs a large domain name blacklist. I decided to use Steven's combined list and found URLHaus when I looked for additional sources it might be missing.

**Comment by dnmTX** [comment]
Steve @StevenBlack 

> Dan @dnmTX and Dima @dimkr we've talked about URLHaus before.

well...never thought about searching for it. Lesson learned 😉 

> URLHaus doesn't list anything from Google, nothing from Doubleclick... It's just, weird.
Your thoughts?

Looks like they're focused on malware domains only with high antivirus detection. Very likely most of them are gathered from VirusTotal. Nothing wrong with that,small list but valuable.Pure example of **quality over quantity**.

> Maybe we should just, do it.

I partially read the license and it looks like they're waiving all their rights,which,in my book is a green light for us here.
Maybe one more e-mail just as a courtesy and if there no response just add it Steve.All of us will be a bit more safer 👍

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX I appreciate your input.

Let's do this.  

Dima @dimkr thank you for this pull request; it makes us better.  Thanks also to Quinn @quinncomendant who first suggested this, back in February, in Issue #1143.

Merging!

**Comment by dimkr** [comment]
Thank you @StevenBlack, looking forward to contributing again. Thank you for maintaining this great project!

**Pull request merged**
