### PR TITLE
Add Maza in readme_template

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by tanrax** [comment]
Do I need to modify README.md?

**Comment by tanrax** [comment]
Removed

**Comment by StevenBlack** [comment]
Thanks Andros @tanrax the all the readme files, 16 in all, are regenerated by the python scripts in this repo.

Thanks for the PR!  Merging!

**Comment by tanrax** [comment]
When you run the script Python? I don't see any changes in the README. Thank you!

**Comment by StevenBlack** [comment]
Andros I run the scripts and commit changes immediately prior to each new release.

The next release is coming shortly...

**Pull request merged**
