### PR TITLE
Remove ban for ITMO University

### PR DESCRIPTION
**Pull request by alexbel**
Wiki page https://en.wikipedia.org/wiki/ITMO_University

### CODE REVIEW

**Comment by funilrys** [comment]
Hello @alexbel !
As you know this project is a compilation of several source therefore I created an issue into Badd-Boyz. I have a whitelisting session later today or tomorrow (Berlin Time) I will look further at that time.

# Occurences of `ifmo.ru`

```
./data/Badd-Boyz-Hosts/hosts <-- entry point
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
./hosts
```

Have a nice day/night.

**Comment by ScriptTiger** [comment]
Just a note to @alexbel, @funilrys is addressing this issue because he is passionate about what he does, but this PR will have to be rejected and closed once it's resolved. If you have similar suggestions in the future, please open an issue for them instead of a PR.

The hosts files in this repo are re-generated regularly with every file version and are the downstream aggregation of multiple sources. Even if your PR was merged, it would be overwritten in a few days by a freshly generated list. Changes must be made on the upstream source files to have an effect, such as the one @funilrys manages.

**Comment by StevenBlack** [comment]
Thanks everyone.

Closing.

**Comment by alexbel** [comment]
Sounds good. Thanks everyone :+1:

**Pull request closed without merging**
