### PR TITLE
Update updateReadme.py

### PR DESCRIPTION
**Pull request by XhmikosR**
* remove duplicate key "issues" in dict literal
* remove trailing whitespaces from the output

The first issue was found with https://lgtm.com/projects/g/StevenBlack/hosts/?mode=list (which is owned by GitHub so feel free to add it to the repo :), the other issues are FPs AFAICT, though)

One last issue I have (but it could be I'm on Windows) is that after running the script some of the Unicode characters aren't outputted properly. For example `Christian Martínez` becomes `Christian MartÃ­nez`. Not sure how to fix this.

### CODE REVIEW

**Comment by funilrys** [comment]
> One last issue I have (but it could be I'm on Windows) is that after running the script some of the Unicode characters aren't outputted properly. For example Christian Martínez becomes Christian MartÃ­nez. Not sure how to fix this.

Which script ?

**Comment by XhmikosR** [comment]
The script I updated here, updateReadme.py.

**Comment by XhmikosR** [comment]
Another issue I see is the script is using backslashes in the URLs on Windows, for example:

```diff
-Unified hosts **+ fakenews** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts) | 52,621 | [link](http://sbc.io/hosts/alternates/fakenews/hosts)
+Unified hosts **+ fakenews** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews\readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews\hosts) | 52,628 | [link](http://sbc.io/hosts/alternates/fakenews\hosts)
```

**Comment by funilrys** [comment]
@XhmikosR I got `Christian Martínez`.

> Another issue I see is the script is using backslashes in the URLs on Windows, for example: 
[...]

Interesting :thinking:.

**Comment by XhmikosR** [comment]
I'll make an issue to track the Windows issues and see if I have some time to look at them, but I'm not really familiar with Python :/

**Comment by funilrys** [comment]
Let us know @XhmikosR ! We will be glad to look into it if you're not familiar with Python.

**Comment by StevenBlack** [comment]
Thanks @XhmikosR!  Thanks Nissar @funilrys for the assistance.

Merging.

**Pull request merged**
