### PR TITLE
Delete .DS_Store from Data

### PR DESCRIPTION
**Pull request by FrancoGag**
If the Data folder is opened in OSX it creates a .DS_Store file and the python script tries to use it a source and returns errors, deleting it solves this issue.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @FrancoGag and thank you for this Pull Request.

I wonder if it's better to just ignore the .DS_Store file, rather than delete it.  Maybe, as a general rule, just ignore `.` files.

**Comment by FrancoGag** [comment]
That is an even better solution, I'll try to code it later

**Comment by FrancoGag** [comment]
Now it no longer deletes .DS_Store and it ignores all hidden files.

I wanted to make a new pull request that included an external whitelist, I'm new with github so I didn't knew it will appear here. Sorry for that.

**Comment by StevenBlack** [comment]
Can someone please test this in Python 3?

Good work @FrancoGag !

**Comment by FrancoGag** [comment]
I already tried it with python 3.5 and it worked fine.
Maybe we should rename removeDups() to removeDupsAndExlc() or something like that.

**Comment by StevenBlack** [comment]
:shipit:

**Pull request merged**
