### PR TITLE
Adding leaky prefix

### PR DESCRIPTION
**Pull request by mys721tx**
Per #982, a list of domains that have at least one A answers from Google
Public DNS has been added to the list.

I made a tool in Go for this task. ([mys721tx/lpc](https://github.com/mys721tx/lpc)). It still needs some work but it can automate most part of the check.

### CODE REVIEW

**Comment by mys721tx** [comment]
Some duplicates were removed, some domains that no longer exist are marked with comments.

**Comment by StevenBlack** [comment]
Hi @mys721tx, thank you for this.

Unfortunately, you've made changes to a generated file.

I think the way this repo works is clear in [the readme](https://github.com/StevenBlack/hosts/blob/master/readme.md).

Our hosts come from a variety of well curated sources, which we amalgamate, de-duplicate, and package in various ways.

The changes you suggest need to happen within curator's repos, not here.

So I must decline this pull request.  But thank you for your efforts!

**Comment by mys721tx** [comment]
The README states that this file is the Steven Black's ad-hoc list, which is not a generated file.

**Comment by StevenBlack** [comment]
My mistake @mys721tx — you're right!  I misread the file path on the [Files changed page](https://github.com/StevenBlack/hosts/pull/984/files).

Reopening.  Thanks for the clarification.

**Comment by StevenBlack** [comment]
Yishen @mys721tx please tell me, what's with the suffix comments?  What do those mean?  How did you establish these, why are they named this way, and why do we want them?

**Comment by mys721tx** [comment]
Those are the errors returned during DNS query. `NXDOMAIN` means the domain in question no longer exist. `SERVFAIL` means that the name server of that domain has failed during query. I am not sure whether those should be removed out right and defer it to you to make that decision.

**Comment by StevenBlack** [comment]
Yishen @mys721tx then I would say, delete the `NXDOMAIN` domain lines, remove the `SERVFAIL` comments, and we're good.

**Comment by mys721tx** [comment]
@StevenBlack removed as requested.

**Comment by StevenBlack** [comment]
Yishen @mys721tx this is all-good.  Thanks!

Merging.

**Pull request merged**
