### PR TITLE
Added Porn Proxy Sites

### PR DESCRIPTION
**Pull request by abhijithvijayan**
Google Pages most relevant results(tested)

### CODE REVIEW

**Comment by funilrys** [comment]
Hi @abhijithvijayan and welcome here!

Unfortunately you did not make #754 an extension ...
Please read more about extensions at https://github.com/StevenBlack/hosts/tree/master/extensions and format your PR as it can't be merged at its current state.

Have a day/night.

Cheers,
Nissar

**Comment by StevenBlack** [comment]
Thanks @abhijithvijayan and thank you for understanding!

Please take note that adding an extension also has an effect on [makeHosts.py](https://github.com/StevenBlack/hosts/blob/master/makeHosts.py) which is hard-coded, one line for each possible variant.

Closing.

**Comment by ScriptTiger** [comment]
If you're using a Google result relevancy sample, I'd also suggest doing a random sample of national top-level and second-level domains, like .com, .ca, .ru, , .au, .jp, .co.uk, etc., as the results may vary.

**Comment by abhijithvijayan** [comment]
@StevenBlack @ScriptTiger I could create a main source repo under my account and create a **hosts**  file and **update.json**  file under **extensions/proxy**  folder and modify makehosts.py script and create a **PR** soon.

Sounds good?

**Comment by ScriptTiger** [comment]
It's up to @StevenBlack, but from previous experience I would say he might want to watch your development with the extension first before accepting a PR to integrate it with the project. He usually looks for a certain level of historical commitment and active curation for extensions that get approved for integration. I would suggest getting your extension together in your repo first, then just opening an issue for it here and not a PR and give it a bit of time to be monitored first while you continue to actively curate it. It's definitely a welcomed addition, so I hope you won't be put off by the time factor, but the active curation element is also a major factor of this project.

**Comment by StevenBlack** [comment]
Thank you @ScriptTiger and yes Abhijith @abhijithvijayan that's right, before I'll accept this I will need a clear and strong commitment from you that you'll keep an eye on your repo, and curate it as required, over the long term.  This means reviewing and adjudicating pull requests on your repo to keep it current and relevant.  

Are you up for that?

**Comment by abhijithvijayan** [comment]
@StevenBlack I could find few proxy sites and I sure as hell can keep an eye on the PRs and keep them updated after inspecting. 
The rest is on the ones that sends the PR.

**Pull request closed without merging**
