### PR TITLE
New ads and tracking sites

### PR DESCRIPTION
**Pull request by anudeepND**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Sorry @anudeepND may I ask you to resubmit?  I merged dfd38474825b prior to seeing this.

**Comment by anudeepND** [comment]
@StevenBlack do I need to create another pull request.

**Comment by ScriptTiger** [comment]
After Steven merged https://github.com/StevenBlack/hosts/commit/dfd38474825beace702b64969d302b3bd7fa2c1b it created a conflict with your PR because it updated the same file, so now it includes things yours does not. If you are only using your current fork of this repo to submit PRs and don't have other branches you are working on personal projects with, the fastest thing to do would be to just delete your current fork and refork it again. Then add your changes to the fresh fork and submit a new PR.

**Comment by anudeepND** [comment]
@ScriptTiger Thanks for the info. I will create a new PR :)

**Comment by StevenBlack** [comment]
@anudeepND and @ScriptTiger um, this is a lot quicker, and easier:

    git rebase -i origin/master

**Comment by StevenBlack** [comment]
@anudeepND and @ScriptTiger more info: [How to Rebase a Pull Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by ScriptTiger** [comment]
I know anudeepND had been using a mobile device for previous PRs, so that was just the mobile solution without having a physical local fork and using an actual git client.

**Pull request closed without merging**
