### PR TITLE
New Data from Mitchell Krog’s - Badd Boyz Hosts list.

### PR DESCRIPTION
**Pull request by mitchellkrogza**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thanks @mitchellkrogza this looks pretty good.

However, eyeballing the list, starting at line 3850, I see this.

What's up with that?

0.0.0.0 xn------7cdbapdecfd4ak1bn0amjffj7afu3y.xn--p1ai
    0.0.0.0 xn-----6kcaacnblni5c5bicdpcmficy.xn--p1ai
    0.0.0.0 xn-----7kcabaipgeakzcss7bjdqdwpfnhv.xn--p1ai
    0.0.0.0 xn-----7kceclhb4abre1b4a0ccl2fxch1a.xn--p1ai
    0.0.0.0 xn-----8kcatubaocd1bneepefojs1h2e.xn--p1ai
    0.0.0.0 xn----7sbaaabaei0cc8aj5bj0bncejx.xn--p1ai
    0.0.0.0 xn----7sbahjd3btneuw1joc.xn--p1ai
    0.0.0.0 xn----7sbaphztdjeboffeiof6c.xn--p1ai
    0.0.0.0 xn----7sbbagbq7bd5aheftfllo4m.xn--p1ai
    0.0.0.0 xn----7sbbahaq9bb5afgiqfliv4m.xn--p1ai
    0.0.0.0 xn----7sbho2agebbhlivy.xn--p1ai
    0.0.0.0 xn----7sbifcamovvfggw9d.xn--p1ai
    0.0.0.0 xn----8sbdbjgb1ap7a9c4czbh.xn--p1acf
    0.0.0.0 xn----8sbhefaln6acifdaon5c6f4axh.xn--p1ai
    0.0.0.0 xn----9sbebi2bvzr7h.xn--p1ai
    0.0.0.0 xn----gtbdb0beu1bb8gj.xn--p1ai
    0.0.0.0 xn----itbeirbjbi7bc6bh2d.xn--p1ai
    0.0.0.0 xn----itbkqkfiq.xn--p1ai
    0.0.0.0 xn--1-8sbcpb0bdm8k6a.xn--p1ai
    0.0.0.0 xn--24-glceagatoq7c2a6ioc.xn--p1ai
    0.0.0.0 xn--80aaafbn2bc2ahdfrfkln6l.xn--p1ai
    0.0.0.0 xn--80aaagvmjabrs1aoc9luc.xn--p1ai
    0.0.0.0 xn--80aaajbdbddwj2alwjieei2afr3v.xn--p1ai
    0.0.0.0 xn--80aaaks3bbhabgbigamdr2h.xn--p1ai
    0.0.0.0 xn--80aafb2a.xn--p1ai
    0.0.0.0 xn--80aagddcgkbcqbad7amllnejg6dya.xn--p1ai
    0.0.0.0 xn--80aanaardaperhcem4a6i.com
    0.0.0.0 xn--80aaomkdl5amcy.xn--p1ai
    0.0.0.0 xn--80ab4aa2g.xn--p1ai
    0.0.0.0 xn--80adaggc5bdhlfamsfdij4p7b.xn--p1ai
    0.0.0.0 xn--80adgcaax6acohn6r.xn--p1ai
    0.0.0.0 xn--80aeahghtf8ac5i.xn--p1ai
    0.0.0.0 xn--80aebbcbcdemfkhba4byaehoejh8dza3v.xn--p1ai
    0.0.0.0 xn--80ahvj9e.xn--p1ai
    0.0.0.0 xn--80aikhbrhr.net
    0.0.0.0 xn--80ajbshivpvn2i.xn--p1ai
    0.0.0.0 xn--80ajjbdhgmudixfjc8c5a9df8b.xn--p1ai
    0.0.0.0 xn--90acenikpebbdd4f6d.xn--p1ai
    0.0.0.0 xn--90adhhccf5aeewt7j.xn--p1ai
    0.0.0.0 xn--b1adccaf1bzj.xn--p1ai
    0.0.0.0 xn--b1ag5cfn.xn--p1ai
    0.0.0.0 xn--b1agm2d.net
    0.0.0.0 xn--c1acygb.xn--p1ai
    0.0.0.0 xn--d1abj0abs9d.in.ua
    0.0.0.0 xn--e1aggki3c.xn--80adxhks
    0.0.0.0 xn--e1ajdckbcx3l.xn--p1ai
    0.0.0.0 xn--e1akkdfpb6a.xn--p1ai
    0.0.0.0 xn--h1aakne2ba.xn--p1ai
    0.0.0.0 xn--h1ahbi.com.ua
    0.0.0.0 xn--hxazdsfy.blogspot.com
    0.0.0.0 xn--l1aengat.xn--p1ai
    0.0.0.0 xn--oogle-wmc.com
    0.0.0.0 xn--q1a.xn--b1aube0e.xn--c1acygb.xn--p1ai

**Comment by mitchellkrogza** [comment]
Hi Steven, those are all foreign domains with special characters. 
screen shot 2017-02-22 at 4 07 22 pm

**Comment by mitchellkrogza** [comment]
You can also do an nslookup on any of them

`nslookup xn--q1a.xn--b1aube0e.xn--c1acygb.xn--p1ai`

```
Non-authoritative answer:
Name:	xn--q1a.xn--b1aube0e.xn--c1acygb.xn--p1ai
Address: 78.110.60.230
```

**Comment by StevenBlack** [comment]
Thanks @mitchellkrogza !

**Comment by mitchellkrogza** [comment]
Thanks Steven, only too glad to contribute.

**Comment by StevenBlack** [comment]
@mitchellkrogza I'm hearing some static because of the inclusion of `kotaku.com` which was added today as part of the merge.

You sure about that one?  It's your call.

**Comment by mitchellkrogza** [comment]
Thanks Steven, a remnant from the original list I started with a year ago. Fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/ea639122317243a15d38d737e7b25a51cbfa34e6

**Comment by PromoFaux** [comment]
@StevenBlack i'm getting reports of false positives since this list inclusion

See here: https://discourse.pi-hole.net/t/latest-blocklists-update-includes-new-source-with-false-positives/1857

@mitchellkrogza What is your process for adding domains to the list?

**Comment by mitchellkrogza** [comment]
Fixed in a number of commits this morning. Apologies, remnants from an original list I started with a year ago. Busy doing a big double-check for false positives against a year's worth of log files.
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commits/master

**Comment by PromoFaux** [comment]
Thanks for the quick response! Apologies for coming at you from all different angles ;)

**Comment by mitchellkrogza** [comment]
Not a problem at all, I've got skin as thick as a rhino 😁  Busy with a major check on my list against a year's worth of logs to rule out any further false positives. Found one or two already, will wait till my bash completes and then send an update out later.

**Comment by mitchellkrogza** [comment]
Also busy running a script to check through entire list for any dead domains / no longer registered / deleted.

**Comment by funilrys** [comment]
@mitchellkr52ogza is #252 Normal ? :smile:

**Comment by mitchellkrogza** [comment]
Over 553 dead / deleted domains removed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/e4c822e9ca6ea6df7d3ea01450ad693a045fba01

**Comment by mitchellkrogza** [comment]
Issue in https://github.com/StevenBlack/hosts/issues/252 fixed with https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/96aa234e149e00365fb12e2531dcf21c9034dc7e

**Comment by StevenBlack** [comment]
Thanks @mitchellkrogza.  Pushed.

**Comment by mitchellkrogza** [comment]
Thanks Steven, wrote a nice little bash which I will run once a month to keep a check on dead / deleted domains. Noticed a few of the other sources are not cleaning up such data. Thanks to this merge yesterday it has helped me find a number of issues, false positives and domains no longer needing to be there to fill up space. Thanks all for your inputs and feedback.

**Comment by PromoFaux** [comment]
I'd be curious to run that script on the compete pi-hole amalgamated list if you don't mind sharing?

**Comment by mitchellkrogza** [comment]
@PromoFaux  I'm what you call a bash basher at best 😁 This simple script just did nslookups on a plain text file from my bad bot blocker list https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Pull_Requests_Here_Please/badreferers.list and I just went through the output file deaddomains.txt manually looking for all NXDOMAIN responses. It could (should) be advanced to take the output file and with a bit of sed, ed and awk to pick out all the NXDOMAIN response, produce a nice clean list and then use that to clean up other lists.

Keep in mind I wrote this in 3 minutes so it certainly needs some work 😀 but I'll get onto that tomorrow probably to save myself when I run it again in a month or so.

```
#!/bin/bash
_input1=./domains.list
for line in $(cat $_input1); do
nslookup ${line} >> deaddomains.txt
done
exit 0
```

**Comment by funilrys** [comment]
New issue #253 @mitchellkrogza :)

**Comment by mitchellkrogza** [comment]
@PromoFaux  found a very cool script to do this - https://www.cyberciti.biz/files/scripts/domain-check-2.txt article at: https://www.cyberciti.biz/tips/domain-check-script.html

**Comment by funilrys** [comment]
@mitchellkrogza I read the script and test it with your `badreferers.list` it seems that there is some case that nslookup is preferable. I haven't tested all possibilities but here's an example.

Here is an exemple:

```sh
$ whois "sonata-arctica.wz.cz"
%  (c) 2006-2017 CZ.NIC, z.s.p.o.
% 
% Intended use of supplied data and information
% 
% Data contained in the domain name register, as well as information
% supplied through public information services of CZ.NIC association,
% are appointed only for purposes connected with Internet network
% administration and operation, or for the purpose of legal or other
% similar proceedings, in process as regards a matter connected
% particularly with holding and using a concrete domain name.
% 
% Full text available at:
% http://www.nic.cz/page/306/intended-use-of-supplied-data-and-information/
% 
% See also a search service at http://www.nic.cz/whois/
% 
% 
% Whoisd Server Version: 3.10.2

%ERROR:101: no entries found
% 
% No entries found.
```
## With `nslookup`
```sh
$ nslookup sonata-arctica.wz.cz
Server:		fd00::3681:c4ff:feca:f421
Address:	fd00::3681:c4ff:feca:f421#53

Non-authoritative answer:
Name:	sonata-arctica.wz.cz
Address: 185.64.219.7
```

Maybe I'm wrong (gonna test it later) but the script can be simplified with the use of the [IANA Root zone Database](https://www.iana.org/domains/root/db) but gonna review the script this afternoon (Berlin Time)

**Comment by mitchellkrogza** [comment]
I'm running that script from cyberbiti for the past 4 hours .... still going 😬 and yes it does produce a lot of false results or failures. I tried in that script switching the whois server on L126 to whois.iana.org and it produced even more failures. nslookup still seems to produce the most solid results thus far. I'm still playing with a solid method of doing this but feel free to share anything you figure out 👍

**Comment by funilrys** [comment]
@mitchellkrogza Since Friday (when I have a bit of time) I work on a script with my idea of using the [IANA Root zone Database](https://www.iana.org/domains/root/db)!

Still testing with your `badreferers.list` (only for now) but I'm pretty happy of what I've done cause most links of your list pass the script without no problem :smiley: but there's some few _(not domain but extensions)_ which I have to take care in the script.

Have to add the following before publishing it [here](https://github.com/funilrys/funceble)

- produce different files output
- generate host file (Let's try to make your life easier :wink: )
- document the code with comments :zipper_mouth_face: 

So just wanted to inform you and I hope I'll publish it this week :gear:

**Comment by mitchellkrogza** [comment]
Excellent @funilrys look forward to seeing it, keep us posted.

**Comment by funilrys** [comment]
Thanks @mitchellkrogza !! Not published yet but gonna publish every [issues](https://github.com/funilrys/funceble/issues) I get from now @mitchellkrogza :)

@PromoFaux Do you have a raw link of generic (without the 0.0.0.0) domains so I can test it ?
Thanks in advance

**Comment by PromoFaux** [comment]
@funilrys Get a pi-hole installed and then you'll have your own list in `/etc/pihole/list.preEventHorizon` 😉 

[here's mine](http://termbin.com/vo9d)

**Comment by funilrys** [comment]
Thanks @PromoFaux :wink: let's test it!

Interesting the Pi-hole project gonna try to integrate it to my other arch when I have time :smile:

**Comment by PromoFaux** [comment]
>gonna try to integrate it to arch when I have time 

User max.bra [has a package up on AUR](https://aur.archlinux.org/packages/pi-hole-server/)

**Comment by funilrys** [comment]
Thanks @PromoFaux but I like to build myself sometimes :wink:

**Comment by funilrys** [comment]
@PromoFaux @mitchellkrogza What is the better for you ?

1) A host file in the following format with custom IP or '0.0.0.0'  (only **ACTIVE** domains)
```
0.0.0.0 domain.com
0.0.0.0 domain-name.com
```
2) A host file in the following format  (only **ACTIVE** domains)
```
domain.com
domain-name.com
```
3) A host file in format **1** _and_ a list of **INACTIVE** domain in format **2**

4) A host file in format **2** _and_ a list of **INACTIVE** domain in format **1**

nb:

- **INACTIVE** ==> Domain is down/dead
- **ACTIVE** ==> Domain not down/dead

Thanks in advance :smiley: :+1:

**Pull request merged**
