### PR TITLE
Backup of old hosts files

### PR DESCRIPTION
**Pull request by gigaslayer131890**
Modified the removeOldHostsFile() function to keep backups of the old hosts file.
This is a proposed enhancement in line with the following issue
https://github.com/StevenBlack/hosts/issues/64

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hey thanks @gigaslayer131890!

**Comment by StevenBlack** [comment]
@gigaslayer131890 since this brings in `shutil` what's your take on changing [this line](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py#L338) in method `moveHostsFileIntoPlace`?

My guess: nah, leave it.

**Comment by gigaslayer131890** [comment]
Thanks for accepting. This was my first open source contribution, so I am glad it went so well.
I would also agree that you can leave that line be. It works, after all. Also, after a quick search, I found out that shutil is slower than subprocess, so you already have the code optimized.

**Comment by StevenBlack** [comment]
That's great @gigaslayer131890.  They say you always remember the first time :-)

**Pull request merged**
