### PR TITLE
Clarify unavoidable bias in the fakenews category

### PR DESCRIPTION
**Pull request by ohadschn**
Related to https://github.com/StevenBlack/hosts/issues/232 and per your comments in https://github.com/StevenBlack/hosts/issues/235:
> I'm open to suggestions to make this more clear.

> I'm always happy to improve things. Pull Requests resonate best with me

I've used the language from the `fakenews` repo almost verbatim: https://github.com/marktron/fakenews#personal-bias-disclosure

### CODE REVIEW

**Comment by StevenBlack** [comment]
Denied.

Closing.

**Comment by ohadschn** [comment]
May I ask why? I practically copy-pasted the disclaimer from `fakenews` repo itself...

**Comment by StevenBlack** [comment]
Because I'm not entertaining pull requests that explicitly ascribe motive, or leanings, of list our curators.  That's never going to happen.  Am I clear Ohad @ohadschn?

**Comment by ohadschn** [comment]
But I'm quoting the guy himself, in his own words, clearly pointing out that said leanings affect the list (presumably with no malicious motive)... What if we removed "left-leaning"?

**Comment by StevenBlack** [comment]
Ohad @ohadschn I am not entertaining pull requests to characterize the Fake News extension in any way. I have no caveats to offer, nor am I seeking guidance from anyone on this.  Furthermore our users are certainly not dummies; they don't need any sort of sophomoric caveats.

I understand the cookie doesn't crumble the way you see it, but that's your problem, not mine.  I am completely comfortable, and I have complete confidence in @marktron's integrity to manage and curate this.  

Nobody here is forcing anybody to use the Fake News packages we make possible.  It's optional.  Downstream users may bundle it in packages they distribute.  Your issue is with them, not us.

**Comment by ohadschn** [comment]
I agree that your users, and people in general, are not dummies. As such, personally I don't think the Fake News extension is needed at all, at least not one as ambitious as the current one (rather than a super obvious one banning straight out scam and UFO sites). In fact this has been suggested before: https://github.com/StevenBlack/hosts/issues/232.

Assuming you do want to keep it though, I think a disclaimer does make sense, especially when it's basically a copy-paste of the one the repo's owner put in his repo expressly for this purpose (presumably you do not consider his own wording sophomoric). I do not consider myself a "dummy" to put it mildly, and yet when I originally downloaded the list I did not dream there would come a day it would actually block what I view as a legit (if biased) news site - on purpose!

Yes, the list is optional, you are not forcing anyone, downstream users can change it and add exception, etc. But the fact is, the vast majority of users will just take a quick look, say "hey I can block fake news, cool" and enable it. Then 3 years later when their friend sends them a link they can't open, it's doubtful they would make this connection.

I have a few open source repos and projects of my own. When people open issues I don't just tell them "hey, it works for me, so it's your problem, nobody's putting a gun to your head to use it" - and I'm sure you're not doing the same in the case of technical issues. In my opinion, while this proposal is not technical, it could potentially benefit a large swath of your users (e.g. US has about 50% conservatives). I'm just one example, there are many more in the issues (random example https://github.com/StevenBlack/hosts/issues/601), and I'm sure you want your work to benefit all people, irrespective of their political viewpoint.

What if we added a more generic caveat that didn't only single out the Fake News extension? Something like:
> These lists are curated by independent people, and might contain categorizations which are erroneous or do not match your definition of the categories below. For example, defining what is or is not "fake news" might be subjective, and as such may contain sites which would be judged differently by another curator. The same can be true for gambling, or even pornography.

**Pull request closed without merging**
