### PR TITLE
add p3a.brave.com

### PR DESCRIPTION
**Pull request by MrRawes**
this is the brave browser's telemetry url

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thank you for this @MrRawes.

I noticed in my Twitter feed that Peter @pgl is [on this case](https://twitter.com/pgl/status/1491118031904600064) and, after a dialog with Brave, he'll list this domain, or not, in due course.  Peter @pgl is a solid list curator and his works are included in our all our lists here.

But thank you anyway for the suggestion.

**Comment by pgl** [comment]
@StevenBlack Thank you for your kind comments and explanation here!

@MrRawes As I said in my email, but to repeat here publicly:

> There are few companies I actually trust online, but Brave is one of
> them. Because of this I don't think I will add this domain to my list.
> Feel free to try and convince me otherwise - I am genuinely open to
> discussion here.

**Comment by StevenBlack** [comment]
Tank you very much Peter @pgl.

I trust you to make this judgment call 👍🏻 I'm comfy either way.

I, too, could be convinced otherwise.

**Comment by MrRawes** [comment]
worth noting incoming.telemetry.mozilla.org is blocked

**Pull request closed without merging**
