### PR TITLE
All the submitted list are regulary updated

### PR DESCRIPTION
**Pull request by spirillen**
I think it's time to call my list stable enough to get into this nicely curated work.

However, as nothing in this world is for sure or certain, I would personally let this PR run in a -dev branch for test period of time.

The contributed list, is relied purely on own work. Which means there are non third party addition to this list.

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @spirillen, I've been watching this, looking for signs of committed, ongoing curation.

I certainly see [many commits](https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/hosts/commits/master).  That's good!

Upon further inspection, it appears the vast majority of commits are by a bot.  The only thing that changes, in the vast majority of commits, is a timestamp is updated.

Within these many trivial commits, I found [this commit](https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/hosts/commit/5c4bc4fc00d77ca4d721ebe195a7ffdb02da077e) which added `recaptcha.net`, three times.

So this doesn't strike me as something that fits the ethos, here.   Care to elaborate?

**Comment by StevenBlack** [comment]
Hi @spirillen this is just an interesting note.   Of the 3351 domains in the proposed source repo, 336 exist already in the amalgamated hosts file.

**Comment by spirillen** [comment]
Hi @StevenBlack 

Sorry for the longer delay in reply, but had my head somewhere else for a couple of days, but for the 

Q: "bot commit"
A: The hosts formatted file it updated through an API call from the master project [matrix](https://gitlab.com/my-privacy-dns/matrix/matrix), but do to a limitation in the choices for when to execute the APi to "only merged into master", they will be some "copies" of the same commits.
But as the [generator script](https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/hosts/blob/master/scripts/generate_hosts.sh) only import from the master (To minimize FP's) you'll only get what have been manually approved. This is simply to avoid FP's as much as ever possible.

Q: Of the 3351 domains in the proposed source repo, 336 exist already in the amalgamated hosts file
A: Actually that's a good thing, as other have discovered 336 of the one I've also have found, but still a low % comparing to other of your sources :+1: and a optimization for +3015 hosts

Other good questions :question:

**Comment by llacb47** [comment]
> Within these many trivial commits, I found [this commit](https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/hosts/commit/5c4bc4fc00d77ca4d721ebe195a7ffdb02da077e) which added `recaptcha.net`, three times.
> 
> So this doesn't strike me as something that fits the ethos, here. Care to elaborate?

**Comment by spirillen** [comment]
PS: If you like any of the other lists from the matrix, we can just put them into the import script :smile: 

PPS: The porn list still need a lot of handcrafting do to a higher number of FP and it might adapt into the [pornhosts](https://gitlab.com/my-privacy-dns/external-sources/pornhosts) project ([github version](https://github.com/Import-External-Sources/pornhosts)). nothing is decided yet.

**Comment by llacb47** [comment]
Blocking `code.jquery.com` is unacceptable in my opinion...

**Comment by StevenBlack** [comment]
@llacb47 really?  Good catch.

Closing.

**Comment by spirillen** [comment]
So that's how you do it @llacb47 and @StevenBlack? stopped talking about mistakes...

That's ok, it makes sense to me now, that you are not that open for giving back only harvesting others work.

As a democrat and worker on opensource, I would have expected a note, to look into it, but your choice.

**Comment by llacb47** [comment]
Hi @spirillen, obviously it was not my choice to close the PR immediately.

A few other false positives:
```
chrome.google.com
storage.googleapis.com
google.com.vn
maps.googleapis.com
maps.gstatic.com
seatgeek.com
feedburner.com
feedburner.google.com
techtarget.com
trustpilot.com
timesofindia.indiatimes.com
androidcentral.com
aolcdn.com
bc.vc
bmovie.cc
c123movies.com
focus.de
goo.gl
kansas.com
keezmovies.com
latimes.com
```

There are more, but I don't have time to curate someone else's list...  I'm noticing a lot of legitimate and semi-legitimate sites are being blocked. There are a lot of URL shorteners on the list for some reason ?

**Comment by StevenBlack** [comment]
@spirillen I've been watching this repo for six weeks.  For six weeks I'm looking for signs of coherent curation.  

Maybe a question for you is, explain the formal curation process that *ever* identifies `code.jquery.com` as malicious.  Or others that @llacb47 identified.

I have concluded that this "source" of bad domains is categorically bullshit.   It has no merit.  Admit it.

**Comment by spirillen** [comment]
`keezmovies.com` accepted :+1: 
`focus.de` accepted :+1: 
`google.com.vn` accepted :+1:  that should stay in the https://gitlab.com/rpz-zones/google.tld only
`androidcentral.com` open for arguments as it looks like yet another FP from an early import
`aolcdn.com` FP from an early import
`c123movies.com` reasons changed :+1: 
`latimes.com` FP from an early import :+1: 
`postimg.cc`  FP from an early import :+1: 
`postimg.cc`  FP from an early import :+1: 
`bc.vc` easylist/easylist/easylist_thirdparty.txt, but admit data have changed :+1: 

`feedburner.com` + `feedburner.google.com` discussed and determined as tracking https://github.com/anudeepND/blacklist/issues/41
`chrome.google.com` tracking + spyware among others.
`storage.googleapis.com` Tracking + spying
`maps.googleapis.com` + `maps.gstatic.com` Tracking + spying + adware

`kansas.com` @llacb47 in #1100 Only way to stop this at hosts level, Temp and better submission is welcome

`seatgeek.com` scam site https://taenk.dk/raadgivning-og-rettigheder/undgaa-billethajer-koeb-dine-billetter-her

`techtarget.com` tracking https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1397

`trustpilot.com` are you serious @llacb47 ? This one of the biggest tracking/spyware/scam/hoax sites that claims to be there for the users, while the reality is quite the opposed.... This is well documented by journalist around the world <= stays

`timesofindia.indiatimes.com` https://github.com/brave/adblock-lists/pull/249/files#diff-3d05cf908db454bc68b7983ddc029cb0R288 https://github.com/AdguardTeam/AdguardFilters/issues/38446
This is absolutely an open for debate, which you also can see at this search https://github.com/search?p=1&q=timesofindia.indiatimes.com&state=closed&type=Issues 

`bmovie.cc` click-spamware https://github.com/webcompat/web-bugs/issues/18969#issuecomment-423867831

`goo.gl` Spy+tracking+redirecting+privacy etc. etc... 

`seekingalpha.com` https://github.com/easylist/easylist/commit/6489947a49ea29002534a1c064c695e2fb0eee5f#commitcomment-35818463 https://github.com/easylist/easylist/commit/6489947a49ea29002534a1c064c695e2fb0eee5f#commitcomment-35818636

Some of these will be fixed, some are staying to learn from. My project is privacy, not allow google and other to collect my privacy data. Since this project have a to different agenda it doesn't seems compatible with each other, and that is it.

To @llacb47 Thanks for the heads up, I do appreciate you comments and findings, but as @StevenBlack pointed out in a another issue, these should have been posted in the respective repo.

@StevenBlack just stop I'm not crawling down to that kindergarten level of "debate", you are solely trying to harvest cheap point on others peoples work without contributing.

- https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/55
- https://github.com/StevenBlack/hosts/issues/1104
- the list is long

And should I start listing the FP in your ./hosts file ? just take the number of NSFW domains listed there. 

I'm done here...

**Comment by spirillen** [comment]
bc.vc = AdWare, Tracking, Redirector

```
Safe Advertising
All advertising is strictly family-safe. Anti-virus and malware servers are scanning the adverts 24/7. 

We give the highest profits to your Desktop and Mobile traffic. 
```

image

**Pull request closed without merging**
