### PR TITLE
add fake investing site

### PR DESCRIPTION
**Pull request by chyla**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Google translation:

> Can I buy shares on the stock exchange without the intermediation of a brokerage house?

> It is not possible to buy shares on the stock exchange without the agency of a brokerage house.

> Only members of the stock exchange, the National Depository for Securities and a company operating a clearing house may be parties to transactions concluded on the stock exchange market. On the other hand, exchange members may be investment firms (including brokerage houses), foreign investment firms and other entities for which the National Depository performs activities in the field of keeping a securities depository or operating a system for registering financial instruments other than securities.

> Investment firms purchase or sell financial instruments on the principal's account based on an agreement for the provision of brokerage services.

> The inability to conclude transactions on the stock exchange without the intermediation of a brokerage house does not mean that you cannot conclude transactions at all without the participation of a broker. It is possible to conclude transactions outside the stock exchange under civil law agreements.

**Comment by StevenBlack** [comment]
Full source of one of these pages:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="[https://fonts.googleapis.com](view-source:https://fonts.googleapis.com/)" />
    <link rel="preconnect" href="[https://fonts.gstatic.com](view-source:https://fonts.gstatic.com/)" crossorigin />
    <link
      href="[https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap](view-source:https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap)"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="[./wfiles/style.css](view-source:https://supdqwepu.com/wfiles/style.css)" />
    <title>Czy mogę kupić akcje na giełdzie bez pośrednictwa biura maklerskiego?</title>
  </head>
  <body>
    <div class="conteiner">
      <h1>
        Czy mogę kupić akcje na giełdzie bez pośrednictwa biura maklerskiego?
      </h1>
      <p>
        Nie jest możliwe kupno akcji na giełdzie bez pośrednictwa biura
        maklerskiego.
      </p>
      <p>
        Stronami transakcji zawieranych na rynku giełdowym mogą być wyłącznie
        członkowie giełdy, Krajowy Depozyt Papierów Wartościowych oraz spółka
        prowadząca izbę rozliczeniową. Członkami giełdy mogą być natomiast firmy
        inwestycyjne (w tym biura maklerskie), zagraniczne firmy inwestycyjne
        oraz inne podmioty, dla których Krajowy Depozyt wykonuje czynności w
        zakresie prowadzenia depozytu papierów wartościowych lub prowadzenia
        systemu rejestracji instrumentów finansowych niebędących papierami
        wartościowymi.
      </p>
      <p>
        Firmy inwestycyjne nabywają lub zbywają instrumenty finansowe na
        rachunek zleceniodawcy w oparciu o umowę o świadczenie usług
        brokerskich.
      </p>
      <p>
        Brak możliwości zawarcia transakcji na giełdzie bez pośrednictwa biura
        maklerskiego nie oznacza, że nie można w ogóle zawierać transakcji bez
        udziału brokera. Możliwe jest zawieranie transakcji poza giełdą w drodze
        umów cywilno-prawnych.
      </p>
     
    </div>
  </body>
</html>
```

**Comment by StevenBlack** [comment]
Thank you for this pull request Adam @chyla.

I'm not seeing anything amiss here. What am I missing?

**Comment by chyla** [comment]
On Facebook there are the following ads: https://yourimageshare.com/ib/IjbveCaMvU

> Od dziś PGNiG zainaugurowało nowy program inwestycyjny dzięki któremu każdy Polak będzie mógł otrzymać od 10000zł na swoją kartę półce minimalną inwestycję w wysokości 1000 zł. Gwarantowany zysk dla akcjonariuszy PGNiG jest teraz realny. Dokonaj inwestycji i otrzymuj dywidendę co miesiąc. Wejdź na stronę!

Which translates to:

> Starting today, PGNiG inaugurated a new investment program thanks to which every Pole will be able to receive a minimum investment of PLN 1,000 on his shelf card. The guaranteed profit for PGNiG shareholders is now real. Make an investment and receive a dividend every month. Go to the website!

The ads points to these domains, thief may preparing the page content or some DNS provider changed the content. In fact, in the message there is nothing about fraud.

**Comment by StevenBlack** [comment]
Thank you Adam @chyla.  Merging.

**Pull request merged**
