### PR TITLE
Allow api.radar.io requests

### PR DESCRIPTION
**Pull request by pcl**
Radar is a legit business that serves up map tiles.

### CODE REVIEW

**Comment by pcl** [comment]
See https://news.ycombinator.com/item?id=37669290

**Comment by StevenBlack** [comment]
Thank you for this Patrick @pcl.

Do you work for Radar?

**Comment by StevenBlack** [comment]
Patrick @pcl I appreciate this pull request but, based on the evidence I see, I decline.

Closing.

**Comment by pcl** [comment]
I don’t.

FYI, according to their privacy FAQ, location tracking is end-user opt-in. However, looking at their privacy policy, the policy claims end-user opt-out. 

https://radar.com/trust
https://radar.com/privacy

Also, unrelatedly — I noticed that some of your hosts files sent the address to 0.0.0.0 and some to 127.0.0.1. I didn’t investigate further to see if you had a reason for the inconsistency.

**Comment by StevenBlack** [comment]
Hi Patrick @pcl all our hosts variants use `0.0.0.0` by default except in a few records at top of file.

That section is verbatim, a unified and de-duplicated collection of entries from OEM hosts files, sourced from a wide variety of operating systems.

Decided not to modify those because hosts files long predate the internet as we know it, and lord knows what scripts exist in userland that may parse hosts files for unimaginable reasons.  So the decision was, let's not gratuitously mess with those.

Note that we provide an [`--ip` flag](https://github.com/StevenBlack/hosts#command-line-options) for people who want to generate something other than our default `0.0.0.0` mapping.

**Comment by kincaidoneil** [comment]
Hello, can this be revisisted? I've had users dissatisfied because this unexpectedly broke part of our web app.

I think there are a couple things worth clarifying:

1. **Radar is opt-in.** Users must explicitly grant geolocation permissions (browser or OS level) or _manually enter their own address_ before Radar can record it. AFAIK, Radar's "tracking" merely is just saving these user-provided coordinates and device IP to their backend, which is pretty similar to the website/app just using a different mapping provider and saving them to its own backend.
2. Radar is for **first-party** location use cases, think like a DoorDash-style delivery app that needs realtime location, or a dating app that asks users for their location to show nearby people. Importantly, again, these are things the user already must opt into at the platform level

**Pull request closed without merging**
