### PR TITLE
GH-1834: Add incoming-telemetry.thunderbird.net

### LINKED ISSUE #1834: Add incoming-telemetry.thunderbird.net
Because I found many queries in my AdBlocker (Pi-Hole) from my family members which doesn't care to disable telemetry in their Thunderbird instance, please add `incoming-telemetry.thunderbird.net` for **Thunderbird** which is still missing. `incoming.telemetry.mozilla.org` for **Firefox** is already included, so it should also include other telemetry domains from Mozilla.

I'll prepare a PR, so you just will have to review and merge. Kind regards!

### PR DESCRIPTION
**Pull request by thomasmerz**
This commit will stop Thunderbird's Telemetry.
Fixes #1834

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi Thomas @thomasmerz thank you for this.

We're mostly an aggregator of other curated sources of hosts.  We regularly amalgamate and deduplicate the combined domains, and repackage them in a variety of targeted ways.

The files you changed are cached and are destroyed each time we fetch for a new release.

So this PR would have no effect.  You made changes to volatile, cached data.

Closing.

**Comment by thomasmerz** [comment]
I understand 👍🏻  You told me already in #1834 that Peter @pgl might take care of this to be maintained properly. This is ok for me. Thanks for your time and explanation!

**Comment by dnmTX** [comment]
> You told me already in #1834 that Peter @pgl might take care of this....

@thomasmerz  that was me,not Steven @StevenBlack 😄

**Comment by thomasmerz** [comment]
@dnmTX , I'm sorry. I wanted to praise **you** for this  👏🏻 

But will @pgl take care of this for sure "automically"? Or do I/we/somebody have to do anything else and what? For me this is not highly important because my blacklist-regex works fine for me:
```
^(.+[_.-])?telemetry[_.-]
```

**Comment by dnmTX** [comment]
@thomasmerz Peter @pgl is usually very prompt.As soon as he can he'll notify us here that the domain was added.
Nothing additional has to be done just a little patience on your end.
Cheers 👍

**Comment by thomasmerz** [comment]
Patience is my middle name 🤣

**Comment by pgl** [comment]
Hey guys, added: https://pgl.yoyo.org/adservers/details.php?hostname=incoming-telemetry.thunderbird.net

Thank you for the nice words @dnmTX. I'm not ALWAYS prompt! But I do try. :)

**Comment by dnmTX** [comment]
> But I do try. :)

We all do our best here. That's what counts. Happy Hollidays Pete @pgl 👍

**Comment by pgl** [comment]
Cheers, you too!

**Comment by StevenBlack** [comment]
Thanks Peter @pgl!

**Pull request closed without merging**
