### PR TITLE
Add Usage for NixOS

### PR DESCRIPTION
**Pull request by sheepfleece**
There is a simpler way to add hosts file on NixOS machines. I thought it would be nice to share.

Also sorry, I wanted to PR into my own branch, but git won't let me, have I done something wrong?

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi @sheepfleece this looks really good.  Thank you for this.  This is perfect.  

Except for one thing.

We have many `readme.md` files in this repo.  See below.  Those are ALL generated by poking data into [`readme_template.md`](https://github.com/StevenBlack/hosts/blob/master/readme_template.md).

Can you please revert this change, and apply it to [`readme_template.md`](https://github.com/StevenBlack/hosts/blob/master/readme_template.md)?  That will be good to merge.

```
alternates/fakenews/readme.md
alternates/fakenews-gambling/readme.md
alternates/fakenews-gambling-porn/readme.md
alternates/fakenews-gambling-porn-social/readme.md
alternates/fakenews-gambling-social/readme.md
alternates/fakenews-porn/readme.md
alternates/fakenews-porn-social/readme.md
alternates/fakenews-social/readme.md
alternates/gambling/readme.md
alternates/gambling-porn/readme.md
alternates/gambling-porn-social/readme.md
alternates/gambling-social/readme.md
alternates/porn/readme.md
alternates/porn-social/readme.md
alternates/social/readme.md
extensions/readme.md
readme.md
```

**Comment by sheepfleece** [comment]
Oh, should have noticed it sooner. There is also a question of which exact url should I specify. Now there is the most restrictive one, simply because this is the one I use. But I'm sure with templates it can be done better (with a note that it can be changed).

**Comment by StevenBlack** [comment]
@sheepfleece can you add a comment, either in the Haskell code, or the text preamble, that this code fetches the full list that includes social media, gambling, porn, etc?  This will kill access to Facebook, Insta, etc.  

I suggest coding for the base list.

**Comment by sheepfleece** [comment]
Base list it is, with a note for other ones.

**Comment by StevenBlack** [comment]
Awesome.  Thanks @sheepfleece!

Merging.

**Pull request merged**
