### PR TITLE
New ad and telemetry sites

### PR DESCRIPTION
**Pull request by anudeepND**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Thanks @anudeepND where do these come from?  Just curious about provenance.

**Comment by anudeepND** [comment]
For more information about Microsoft domains can be seen [here](https://docs.microsoft.com/en-us/windows/configuration/manage-windows-endpoints-version-1709)

1. `sqm.telemetry.microsoft.com` Software Quality Metrics (SQM) from Microsoft. It is used by Windows applications to recollect telemetry data.

2. `adservice.google.co.in` is Google ad domain, these type of domain in region specific. For example same variant of domain found in Germany is `adservice.google.co.de`

3. `apiv2.moengage.com`
     `api.moengage.com`
     `apiv3.moengage.com`
 From moengage.com, "Using MoEngage's advanced user analytics and engagement platforms (push, in-app & web push), we have been able to deliver on the ... "
I don't know whether the push notifications will get blocked.

4. `logs.gaana.com` Gaana is a music streaming service, this domain is used to upload telemetry data to their server. 

5. `ase.clmbtech.com`
     `static.clmbtech.com`
These domains are used to record clicks and deliver static ads on a webpage. 

6. `settings.crashlytics.com`
     `reports.crashlytics.com`
These domains are related to crashlytics.com error reporting services, let me know if you want to remove this.

7. `in-starlive.videoplaza.tv`
     `in-starlive-preroll.videoplaza.tv`
      More information can be found here [here](http://www.ooyala.com/videoplaza)

8. `ibeat.indiatimes.com`
It's used to deliver JavaScript tracking code across website (Majority of this domain can be found in Indian news websites)

9. `api.taplytics.com`
Possible telemetry service - https://taplytics.com/

10. `udm.scorecardresearch.com`
https://www.theguardian.com/technology/2012/apr/23/scorecardresearch-tracking-trackers-cookies-web-monitoring

11. `decide.mixpanel.com`
Another tracking company - https://mixpanel.com

12. `cdn.auditude.com`
Ad company acquired by Adobe, "Auditude, Inc. provides online video advertising technology and monetization solutions for content owners and distributors. "

13. `api.branch.io`
From branch.io - "The mobile marketing and linking platform to supercharge your app growth and seamlessly plug into your marketing stack"
Let  me know if you want to remove this domain. (It says something about deep links, I don't know what it is can you please explain?)

14. `e-ssl.apsalar.com`
`t.appsflyer.com`
`cdn-settings.segment.com`
Tracking sites, majorly used in android apps. 

All these domains were recorded by my Pi-Hole and these domains are originated from the device and service I use.

**Comment by dnmTX** [comment]
Hmm.....wondering how long it will take until the "CEO's" show up here and start educating us in how telemetry works?

**Comment by StevenBlack** [comment]
Thank you @anudeepND.  Merging.

**Pull request merged**
