### PR TITLE
Gentoo information

### PR DESCRIPTION
**Pull request by PF4Public**

### CODE REVIEW

**Comment by Laicure** [comment]
wut?
Correct me if I am wrong.
Is that a hosts file location or you just advertised your hosts repo?

**Comment by dnmTX** [comment]
@Laicure  this is just a set up of the hosts here for anyone using Gentoo Linux. Nothing wrong alternatives like this one to be listed here.

**Comment by PF4Public** [comment]
@Laicure Instead of doing manual edits, one could simply install `sb-hosts` from my overlay and allow Gentoo's portage to take care of updating `/etc/hosts`. This is Gentoo specific ofcourse.

**Comment by funilrys** [comment]
@Laicure probably means: Do we need this new layer to the chain of trust?
I won't comment more on that as it will probably open a new discussion which we don't want here (or now).

I have to focus on something else right now but #1003 is still on my list of things to do. Indeed, with #1003, we could programmatically (for example with a new version of the script) install, flush, restart for each distribution as long as we have rights and a clear explanation of how to work from a specific distribution (won't be that hard normally). 

Anyway, @PF4Public Thanks for your PR and your time this is awesome! Can you just write your changes into the `readme_template` file instead of the `readme` one?

It's yours Steve @StevenBlack.


Cheers,
Nissar

**Comment by StevenBlack** [comment]
Hi @PF4Public, thanks, but Nissar @funilrys is correct.  `readme.md` is generative; we use [`readme_template.md`](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) to generate it.  That's where edits should be made.

Because we have many `readme.md` files in this repo.

```
alternates/fakenews/readme.md
alternates/fakenews-gambling/readme.md
alternates/fakenews-gambling-porn/readme.md
alternates/fakenews-gambling-porn-social/readme.md
alternates/fakenews-gambling-social/readme.md
alternates/fakenews-porn/readme.md
alternates/fakenews-porn-social/readme.md
alternates/fakenews-social/readme.md
alternates/gambling/readme.md
alternates/gambling-porn/readme.md
alternates/gambling-porn-social/readme.md
alternates/gambling-social/readme.md
alternates/porn/readme.md
alternates/porn-social/readme.md
alternates/social/readme.md
extensions/readme.md
readme.md
```

**Comment by StevenBlack** [comment]
Thanks @PF4Public.  Merging.

**Comment by PF4Public** [comment]
>Can you just write your changes into the readme_template file instead of the readme one?

I'm really sorry, I should have read `contributing.md` and `codebase_structure.md` beforehead.

@funilrys 
>Do we need this new layer to the chain of trust?

That isn't! See for yourself: [sb-hosts-2.5.21.ebuild](https://github.com/PF4Public/gentoo-overlay/blob/master/net-misc/sb-hosts/sb-hosts-2.5.21.ebuild). I would rather call it a convenience. At least for me.

With respect to #1003 I must admit, that having such a thing is a good thing. But from the packaging standpoint it would suffice to have a simple script, that could concatenate (but not download) various hosts and merge them with local hosts. I'm not telling you what to do of-course, because you already do a great job! I'll just adapt my ebuild file to what you end up with.

**Pull request merged**
