### PR TITLE
Add Travis SVG to README

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

### CODE REVIEW

**Comment by gfyoung** [comment]
@StevenBlack : Can confirm that Travis is working and green!

**Comment by StevenBlack** [comment]
That needs to go in `readme_template.md` as all the `readme.md` are generative 😄

**Comment by gfyoung** [comment]
Ah, got it.  Fixed.

**Comment by StevenBlack** [comment]
Perfect!  Thanks @gfyoung 🏅

**Pull request merged**
