### PR TITLE
Removed my list from this project per #881

### PR DESCRIPTION
**Pull request by lightswitch05**

### CODE REVIEW

**Comment by StevenBlack** [comment]
Merged.

**Comment by anudeepND** [comment]
:confused:

**Comment by dnmTX** [comment]
@lightswitch05  &  @StevenBlack  any chance to smooth things out and get back where we were?
Can't let some privacy abusing company win again. Isn't it what we all do here,help protecting everyone's privacy,or what really left of it?

**Comment by StevenBlack** [comment]
I'm not comfortable blocking the root domain of a really good, mission critical component in the software development space.  We aren't talking about Crashlytics here.

**Pull request merged**
