### PR TITLE
 updateHostsFile.py:: revert encoding

### PR DESCRIPTION
**Pull request by FadeMind**
@funilrys @StevenBlack please apply this revert cause final PR #520 after lastest changes unable download from somewherewhocares.org.

This PR revert encoding section to WORKING for me code.

Regards

Tomasz

### CODE REVIEW

**Comment by FadeMind** [comment]
Looks like Travis CI freak out LIKE after lastest changes with #520

**Comment by funilrys** [comment]
STOP I did those change for a reason .... Let me review it personally once back home @StevenBlack. I tested #520 over 4 networks 2 countries (France amd Germany) and 5 computers (32 bits and 64 bits) so I do not understand this.

Also not that this reversion is really bad cause this do nit respect original file structure if we have more that 1 '#' at the end of a line.

Plus there is a reason that I check for tabulation before space.

**Comment by funilrys** [comment]
@StevenBlack just give a quick look at the tests and they explain my changes by themselves ...

**Comment by StevenBlack** [comment]
@funilrys it's all-good.  I'm not reverting anything 😄.

Just need to figure out what's up with this one provider.

**Comment by FadeMind** [comment]
@StevenBlack @funilrys when I using final code (not reverted) then I cannot download from somweherewhocares and hphosts. 

After revert this, downloading and creating hosts file went fine, so don't be angry at me.

**Comment by funilrys** [comment]
I was not angry it's just the morning out of town because of personal reason 😅 sorry if I offensed you @FadeMind ...

What do you got as exception ? 🤔

**Comment by FadeMind** [comment]
```
[fademind@manjaro hosts]$ python updateHostsFile.py -a -n
Traceback (most recent call last):
  File "updateHostsFile.py", line 1485, in <module>
    main()
  File "updateHostsFile.py", line 192, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 652, in create_initial_file
    write_data(merge_file, curFile.read())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 17997931: invalid continuation byte
```

**Comment by funilrys** [comment]
Then the problem is not the function you're reverting ...

**Comment by FadeMind** [comment]
Previous post is basic of final code (merged in #520 ) When I revert decode to Your first commit in #520, then all is good.

**Comment by FadeMind** [comment]
@funilrys  SIMPLE 😆 

Changing at 1165 to
```
for separator in [' ', '\t']:
```
resolved issue. 

CC @StevenBlack  @funilrys

**Comment by funilrys** [comment]
Please take a look at the tests ... That doesn't resolve anything ...

**Comment by funilrys** [comment]
Okay I'm back home let me check everything ...

**Comment by FadeMind** [comment]
I used original file and switch to `for separator in [' ', '\t']:` 
and all went fine:

```
[fademind@manjaro ~]$ cat ~/bin/uhf 
#!/usr/bin/env bash
cd $HOME/GitHub/mnjpkgbuilds/00-HSTS.EXT/
python updateHostsFile.py -a -c -r -f 
```
```
[fademind@manjaro ~]$ uhf
Updating source data/add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source data/someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source data/CoinBlockerLists from https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser
Updating source data/adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source data/tyzbit from https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts
Updating source data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source data/add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source data/UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
Updating source data/mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source data/add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source data/yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source data/KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source data/Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source data/malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source data/Spotify-Ad-free from https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotifynulled.txt
Updating source data/CoinBlockerList from https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser
Updating source data/add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
==>0.0.0.0 130.211.230.53<==
==>0.0.0.0 12.170.116.68<==
==>0.0.0.0 164.109.51.67<==
==>0.0.0.0 5.100.249.215<==
==>0.0.0.0 74.112.173.77<==
==>0.0.0.0 91.205.157.38<==
==>0.0.0.0 91.212.132.230<==
Success! The hosts file has been saved in folder 
It contains 55,549 unique entries.
Moving the file requires administrative privileges. You might need to enter your password.
Flushing the DNS cache to utilize new hosts file...
Flushing the DNS cache requires administrative privileges. You might need to enter your password.
Flushing the DNS cache by restarting NetworkManager.service succeeded
Flushing the DNS cache by restarting dnsmasq.service succeeded
Flushing the DNS cache by restarting NetworkManager.service succeeded
Flushing the DNS cache by restarting dnsmasq.service succeeded
```

**Comment by funilrys** [comment]
Yup @FadeMind but we are in a global environment ... if the tests are not passed then it's almost sure that it will fail for everybody if we merge this ...

**Comment by FadeMind** [comment]
BUT See here: https://github.com/StevenBlack/hosts/pull/520/commits
screenshot_20180304_095324.

@StevenBlack merged this code anyway. Seems to be little switch letters and marks for working fine.

**Comment by funilrys** [comment]
@FadeMind Please take a look the test itself ... it's a Travis CI issue : https://travis-ci.org/StevenBlack/hosts/jobs/348731441

**Comment by FadeMind** [comment]
```
The command "eval git fetch origin +refs/pull/520/merge: " failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/520/merge
The command "eval git fetch origin +refs/pull/520/merge: " failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/520/merge
The command "eval git fetch origin +refs/pull/520/merge: " failed 3 times.
The command "git fetch origin +refs/pull/520/merge:" failed and exited with 128 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```

So, thats why is happen.

**Comment by funilrys** [comment]
@FadeMind yes all of those merge issues are by Travis CI ... It did not even start the local code tests ...

**Comment by FadeMind** [comment]
Anyway

Diff is trivial:
screenshot_20180304_100135
Works fine for my end. 

@StevenBlack please review, test and apply if you like. Thanks for patient ;)

**Comment by funilrys** [comment]
The issue is not about that ... 

The real issue is a line like

```
0.0.0.0(space)domain(tablulation(s) and spaces)# comments`
```

I'm writing the fix right now... will send PR before the end of the day ...

**Comment by FadeMind** [comment]
@funilrys so, closing this PR now?? :>

**Comment by funilrys** [comment]
To clarify @FadeMind If we apply your patch, the day we encounter

```
0.0.0.0(tabulations)domain(spaces)# comments`
```

We will have the same issue but in the other way so I may have to refactor that function cause I did not even think about that as I did not write the tests for your case...

**Comment by FadeMind** [comment]
@StevenBlack @funilrys  closing this PR cause #527 pending...

**Pull request closed without merging**
