### PR TITLE
Document all functions in Python scripts

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

Also re-organized a couple of functions at the top of `updateHostsFile.py` into the helper functions section and moved the `main` method to the top for consistency with `updateReadme.py`.

Picked some other minor documentation changes along the way.

### CODE REVIEW

**Comment by gfyoung** [comment]
@StevenBlack : Do you have any updates on this PR?  Was there anything that needed to be fixed before merging this?

**Comment by StevenBlack** [comment]
LGTM.  I just haven't had a chance to test this one.

**Comment by gfyoung** [comment]
@StevenBlack : Rebased and ready to go.

**Comment by gfyoung** [comment]
@StevenBlack : Rebased this PR again to include recent merges.  Let me know if there's anything that should be changed before merging.

**Comment by StevenBlack** [comment]
Thanks for your patience @gfyoung.

This took awhile to merge because there are code changes mixed-in with comment changes and that muddled the PR to a large degree.

**Comment by gfyoung** [comment]
@StevenBlack : Sure thing!  Yeah, when writing up the documentation, there were some extraneous lines of code that didn't quite make sense with the documentation, so I fixed them too.

**Pull request merged**
