### PR TITLE
stevenblack: hosts: add alienvault IoC, sorted, fix issue

### PR DESCRIPTION
**Pull request by scafroglia93**
1- Added some Alienvault IoC (premium subscriber IoC)
2- Alphetical Sorted
3- Removed double entries
4- Fix some issue there are 3 domain with 0.0.0.0.0.0

Signed-off-by: scafroglia93 <scafroglia57@gmail.com>

### CODE REVIEW

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93, please don't sort the file alphabetically.

I use [ghosts](https://github.com/StevenBlack/ghosts) to sort the file, which order by domain, tld, then subdomains.

I can't accept this PR because I cannot evaluate what's new, and what's removed.  The diff is just a big mess.

I'm sorry.  Can you please resubmit with just the changes, without also scrambling the file?  Thanks.

**Comment by StevenBlack** [comment]
Also, @scafroglia93, what does `IoC` mean?

**Comment by dnmTX** [comment]
> what does IoC mean?

From AlienVault:
AlienVault
😉

**Comment by scafroglia93** [comment]
pr done right now

**Pull request closed without merging**
