### PR TITLE
update Reloading hosts file instructions for Linux

### PR DESCRIPTION
**Pull request by FadeMind**
Just update **Reloading hosts file instructions for Linux** in `readme_template.md` file.

Regards

### CODE REVIEW

**Comment by qutorial** [comment]
Well, Ubuntu reloads the hosts file automatically once it is modified, as far as I know..

**Comment by Gitoffthelawn** [comment]
@FadeMind and @qutorial Do you have any insight in how to solve https://github.com/Free-Software-for-Android/AdAway/issues/552 ?

**Comment by qutorial** [comment]
@Gitoffthelawn I have adaway disabled. I have manually installed a hosta file with more than 400K hosts and it does a good job in my case.

**Comment by Gitoffthelawn** [comment]
@qutorial Thanks.  400K hosts?!?  On an Android device or a full Ubuntu box?

If Android, do you have a way to have a new hosts file recognized without rebooting?

**Comment by qutorial** [comment]
@Gitoffthelawn :) Below Android you have a decent Linux core. Running Java VM, or extensions inside Firefox (tried it?) is way more computationally complex than working in C with a long hosts file. It works absolutely fine. I generate this file with a fork of this project: https://github.com/qutorial/hoststool and manually copy it to my old Android tablet. 
I did it just once and the changes took effect immediately. So I have never confronted the problem to flush the DNS cache. Sorry, no tips here. 
This was also the day I deleted opera mini, as they proxy connections and serve you ads despite your host blocks DNS queries to the hosts with these ads. As a result I had really disgusting ads on the top side of my favorite news website. Using Firefox for Android with extensions now. uBlock origin would be an example.

**Comment by Gitoffthelawn** [comment]
@qutorial Thanks for the details.  Also thanks for the info on Opera Mini... I didn't know that.

As to my (implied) performance question with a hosts file with 400K items, I was thinking of the performance of the OS networking layer once it is using such a large hosts file.  It definitely would depend on how efficiently the OS performs lookups in the list.

It's interesting that your changes took effect immediately on Android; the AdAway project (https://github.com/Free-Software-for-Android/AdAway) has not had success in updating hosts without rebooting due to DNS caching.  Maybe you got lucky or nothing was cached. :-)

**Comment by qutorial** [comment]
@Gitoffthelawn I think so, indeed, I got lucky probably. Speaking of the network performance. I notice no difference in practice. Maybe caching helps here as well.

**Comment by Gitoffthelawn** [comment]
@qutorial Thanks. Are you doing any special caching, or just using the default OS caching?

**Comment by qutorial** [comment]
@Gitoffthelawn I meant the default OS caching.

**Comment by Gitoffthelawn** [comment]
@qutorial Thanks.  Glad to hear that the OS can handle such large *hosts* lists.

BTW https://github.com/Free-Software-for-Android/AdAway/issues/552 is still open.

**Pull request merged**
